// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../actionlib_msgs/msg//GoalStatusArray.msg
// DO NOT EDIT!
package actionlib_msgs

type _MsgGoalStatusArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGoalStatusArray) Text() string {
	return t.text
}

func (t *_MsgGoalStatusArray) Name() string {
	return t.name
}

func (t *_MsgGoalStatusArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGoalStatusArray) NewMessage() ros.Message {
	m := new(GoalStatusArray)

	return m
}

var (
	MsgGoalStatusArray = &_MsgGoalStatusArray{
		`# Stores the statuses for goals that are currently being tracked
# by an action server
Header header
GoalStatus[] status_list

`,
		"actionlib_msgs/GoalStatusArray",
		"12ef789174f5252c94b427cdb93b2d0a",
	}
)

type GoalStatusArray struct {
	Header     Header
	StatusList []GoalStatus
}

func (m *GoalStatusArray) Type() ros.MessageType {
	return MsgGoalStatusArray
}

func (m *GoalStatusArray) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// StatusList
	binary.Write(buf, binary.LittleEndian, uint32(len(m.StatusList)))
	for _, e := range m.StatusList {
		if err = e.Serialize(buf); err != nil {
			return err
		}
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// StatusList
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.StatusList = make([]GoalStatus, int(size))
	for i := 0; i < int(size); i++ {
		if err = m.StatusList[i].Deserialize(buf); err != nil {
			return err
		}
	}

	return
}
