// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../sensor_msgs/msg//Imu.msg
// DO NOT EDIT!
package sensor_msgs

type _MsgImu struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgImu) Text() string {
	return t.text
}

func (t *_MsgImu) Name() string {
	return t.name
}

func (t *_MsgImu) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgImu) NewMessage() ros.Message {
	m := new(Imu)

	return m
}

var (
	MsgImu = &_MsgImu{
		`# This is a message to hold data from an IMU (Inertial Measurement Unit)
#
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec
#
# If the covariance of the measurement is known, it should be filled in (if all you know is the 
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)
# A covariance matrix of all zeros will be interpreted as "covariance unknown", and to use the
# data a covariance will have to be assumed or gotten from some other source
#
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation 
# estimate), please set element 0 of the associated covariance matrix to -1
# If you are interpreting this message, please check for a value of -1 in the first element of each 
# covariance matrix, and disregard the associated estimate.

Header header

geometry_msgs/Quaternion orientation
float64[9] orientation_covariance # Row major about x, y, z axes

geometry_msgs/Vector3 angular_velocity
float64[9] angular_velocity_covariance # Row major about x, y, z axes

geometry_msgs/Vector3 linear_acceleration
float64[9] linear_acceleration_covariance # Row major x, y z 
`,
		"sensor_msgs/Imu",
		"e151f4f1e424591263d54004d2754410",
	}
)

type Imu struct {
	Header                       Header
	Orientation                  geometry_msgs.Quaternion
	OrientationCovariance        [9]float64
	AngularVelocity              geometry_msgs.Vector3
	AngularVelocityCovariance    [9]float64
	LinearAcceleration           geometry_msgs.Vector3
	LinearAccelerationCovariance [9]float64
}

func (m *Imu) Type() ros.MessageType {
	return MsgImu
}

func (m *Imu) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Orientation
	if err = m.Orientation.Serialize(buf); err != nil {
		return err
	}

	// OrientationCovariance
	binary.Write(buf, binary.LittleEndian, uint32(len(m.OrientationCovariance)))
	for _, e := range m.OrientationCovariance {
		binary.Write(buf, binary.LittleEndian, e)
	}

	// AngularVelocity
	if err = m.AngularVelocity.Serialize(buf); err != nil {
		return err
	}

	// AngularVelocityCovariance
	binary.Write(buf, binary.LittleEndian, uint32(len(m.AngularVelocityCovariance)))
	for _, e := range m.AngularVelocityCovariance {
		binary.Write(buf, binary.LittleEndian, e)
	}

	// LinearAcceleration
	if err = m.LinearAcceleration.Serialize(buf); err != nil {
		return err
	}

	// LinearAccelerationCovariance
	binary.Write(buf, binary.LittleEndian, uint32(len(m.LinearAccelerationCovariance)))
	for _, e := range m.LinearAccelerationCovariance {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Orientation
	if err = m.Orientation.Deserialize(buf); err != nil {
		return err
	}

	// OrientationCovariance
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	if size > 9 {
		return fmt.Errorf("array size for OrientationCovariance too large: expected=9, got=%d", size)
	}
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.OrientationCovariance[i]); err != nil {
			return err
		}
	}

	// AngularVelocity
	if err = m.AngularVelocity.Deserialize(buf); err != nil {
		return err
	}

	// AngularVelocityCovariance
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	if size > 9 {
		return fmt.Errorf("array size for AngularVelocityCovariance too large: expected=9, got=%d", size)
	}
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.AngularVelocityCovariance[i]); err != nil {
			return err
		}
	}

	// LinearAcceleration
	if err = m.LinearAcceleration.Deserialize(buf); err != nil {
		return err
	}

	// LinearAccelerationCovariance
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	if size > 9 {
		return fmt.Errorf("array size for LinearAccelerationCovariance too large: expected=9, got=%d", size)
	}
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.LinearAccelerationCovariance[i]); err != nil {
			return err
		}
	}

	return
}
