// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../sensor_msgs/msg//RegionOfInterest.msg
// DO NOT EDIT!
package sensor_msgs

type _MsgRegionOfInterest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgRegionOfInterest) Text() string {
	return t.text
}

func (t *_MsgRegionOfInterest) Name() string {
	return t.name
}

func (t *_MsgRegionOfInterest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgRegionOfInterest) NewMessage() ros.Message {
	m := new(RegionOfInterest)

	return m
}

var (
	MsgRegionOfInterest = &_MsgRegionOfInterest{
		`# This message is used to specify a region of interest within an image.
#
# When used to specify the ROI setting of the camera when the image was
# taken, the height and width fields should either match the height and
# width fields for the associated image; or height = width = 0
# indicates that the full resolution image was captured.

uint32 x_offset  # Leftmost pixel of the ROI
                 # (0 if the ROI includes the left edge of the image)
uint32 y_offset  # Topmost pixel of the ROI
                 # (0 if the ROI includes the top edge of the image)
uint32 height    # Height of ROI
uint32 width     # Width of ROI

# True if a distinct rectified ROI should be calculated from the "raw"
# ROI in this message. Typically this should be False if the full image
# is captured (ROI not used), and True if a subwindow is captured (ROI
# used).
bool do_rectify
`,
		"sensor_msgs/RegionOfInterest",
		"7cfa19dc46ace2888bcd1b7980b9e5cf",
	}
)

type RegionOfInterest struct {
	XOffset   uint32
	YOffset   uint32
	Height    uint32
	Width     uint32
	DoRectify bool
}

func (m *RegionOfInterest) Type() ros.MessageType {
	return MsgRegionOfInterest
}

func (m *RegionOfInterest) Serialize(buf *bytes.Buffer) (err error) {
	// XOffset
	binary.Write(buf, binary.LittleEndian, m.XOffset)

	// YOffset
	binary.Write(buf, binary.LittleEndian, m.YOffset)

	// Height
	binary.Write(buf, binary.LittleEndian, m.Height)

	// Width
	binary.Write(buf, binary.LittleEndian, m.Width)

	// DoRectify
	binary.Write(buf, binary.LittleEndian, m.DoRectify)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// XOffset
	if err = binary.Read(buf, binary.LittleEndian, &m.XOffset); err != nil {
		return err
	}

	// YOffset
	if err = binary.Read(buf, binary.LittleEndian, &m.YOffset); err != nil {
		return err
	}

	// Height
	if err = binary.Read(buf, binary.LittleEndian, &m.Height); err != nil {
		return err
	}

	// Width
	if err = binary.Read(buf, binary.LittleEndian, &m.Width); err != nil {
		return err
	}

	// DoRectify
	if err = binary.Read(buf, binary.LittleEndian, &m.DoRectify); err != nil {
		return err
	}

	return
}
