// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../visualization_msgs/msg//MenuEntry.msg
// DO NOT EDIT!
package visualization_msgs

type _MsgMenuEntry struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgMenuEntry) Text() string {
	return t.text
}

func (t *_MsgMenuEntry) Name() string {
	return t.name
}

func (t *_MsgMenuEntry) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgMenuEntry) NewMessage() ros.Message {
	m := new(MenuEntry)

	return m
}

var (
	MsgMenuEntry = &_MsgMenuEntry{
		`# MenuEntry message.

# Each InteractiveMarker message has an array of MenuEntry messages.
# A collection of MenuEntries together describe a
# menu/submenu/subsubmenu/etc tree, though they are stored in a flat
# array.  The tree structure is represented by giving each menu entry
# an ID number and a "parent_id" field.  Top-level entries are the
# ones with parent_id = 0.  Menu entries are ordered within their
# level the same way they are ordered in the containing array.  Parent
# entries must appear before their children.

# Example:
# - id = 3
#   parent_id = 0
#   title = "fun"
# - id = 2
#   parent_id = 0
#   title = "robot"
# - id = 4
#   parent_id = 2
#   title = "pr2"
# - id = 5
#   parent_id = 2
#   title = "turtle"
#
# Gives a menu tree like this:
#  - fun
#  - robot
#    - pr2
#    - turtle

# ID is a number for each menu entry.  Must be unique within the
# control, and should never be 0.
uint32 id

# ID of the parent of this menu entry, if it is a submenu.  If this
# menu entry is a top-level entry, set parent_id to 0.
uint32 parent_id

# menu / entry title
string title

# Arguments to command indicated by command_type (below)
string command

# Command_type stores the type of response desired when this menu
# entry is clicked.
# FEEDBACK: send an InteractiveMarkerFeedback message with menu_entry_id set to this entry's id.
# ROSRUN: execute "rosrun" with arguments given in the command field (above).
# ROSLAUNCH: execute "roslaunch" with arguments given in the command field (above).
uint8 FEEDBACK=0
uint8 ROSRUN=1
uint8 ROSLAUNCH=2
uint8 command_type
`,
		"visualization_msgs/MenuEntry",
		"79f8c1595a875595df6690a4d1a3ac66",
	}
)

type MenuEntry struct {
	ID          uint32
	ParentID    uint32
	Title       string
	Command     string
	CommandType uint8
}

func (m *MenuEntry) Type() ros.MessageType {
	return MsgMenuEntry
}

func (m *MenuEntry) Serialize(buf *bytes.Buffer) (err error) {
	// ID
	binary.Write(buf, binary.LittleEndian, m.ID)

	// ParentID
	binary.Write(buf, binary.LittleEndian, m.ParentID)

	// Title
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.Title))))
	buf.Write([]byte(m.Title))

	// Command
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.Command))))
	buf.Write([]byte(m.Command))

	// CommandType
	binary.Write(buf, binary.LittleEndian, m.CommandType)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// ID
	if err = binary.Read(buf, binary.LittleEndian, &m.ID); err != nil {
		return err
	}

	// ParentID
	if err = binary.Read(buf, binary.LittleEndian, &m.ParentID); err != nil {
		return err
	}

	// Title
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	data := make([]byte, int(size))
	if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
		return err
	}
	m.Title = string(data)

	// Command
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	data := make([]byte, int(size))
	if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
		return err
	}
	m.Command = string(data)

	// CommandType
	if err = binary.Read(buf, binary.LittleEndian, &m.CommandType); err != nil {
		return err
	}

	return
}
