// Code generated by ros-gen-go.
// source: AccelStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgAccelStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgAccelStamped) Text() string {
	return t.text
}

func (t *_MsgAccelStamped) Name() string {
	return t.name
}

func (t *_MsgAccelStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgAccelStamped) NewMessage() ros.Message {
	m := new(AccelStamped)

	return m
}

var (
	MsgAccelStamped = &_MsgAccelStamped{
		`# An accel with reference coordinate frame and timestamp
Header header
Accel accel
`,
		"geometry_msgs/AccelStamped",
		"b50c8c69ae37bb74d3cffd798577ca70",
	}
)

type AccelStamped struct {
	Header std_msgs.Header
	Accel  Accel
}

func (m *AccelStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "Accel", &m.Accel); err != nil {
		return err
	}

	return
}

func (m *AccelStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Accel
	if err = ros.DeserializeMessageField(r, "Accel", &m.Accel); err != nil {
		return err
	}

	return
}
