// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//AccelWithCovarianceStamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgAccelWithCovarianceStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgAccelWithCovarianceStamped) Text() string {
	return t.text
}

func (t *_MsgAccelWithCovarianceStamped) Name() string {
	return t.name
}

func (t *_MsgAccelWithCovarianceStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgAccelWithCovarianceStamped) NewMessage() ros.Message {
	m := new(AccelWithCovarianceStamped)

	return m
}

var (
	MsgAccelWithCovarianceStamped = &_MsgAccelWithCovarianceStamped{
		`# This represents an estimated accel with reference coordinate frame and timestamp.
Header header
AccelWithCovariance accel
`,
		"geometry_msgs/AccelWithCovarianceStamped",
		"cf7b852cab243d76000e69f42f2700f6",
	}
)

type AccelWithCovarianceStamped struct {
	Header Header
	Accel  AccelWithCovariance
}

func (m *AccelWithCovarianceStamped) Type() ros.MessageType {
	return MsgAccelWithCovarianceStamped
}

func (m *AccelWithCovarianceStamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Accel
	if err = m.Accel.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Accel
	if err = m.Accel.Deserialize(buf); err != nil {
		return err
	}

	return
}
