// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//AccelStamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgAccelStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgAccelStamped) Text() string {
	return t.text
}

func (t *_MsgAccelStamped) Name() string {
	return t.name
}

func (t *_MsgAccelStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgAccelStamped) NewMessage() ros.Message {
	m := new(AccelStamped)

	return m
}

var (
	MsgAccelStamped = &_MsgAccelStamped{
		`# An accel with reference coordinate frame and timestamp
Header header
Accel accel
`,
		"geometry_msgs/AccelStamped",
		"b50c8c69ae37bb74d3cffd798577ca70",
	}
)

type AccelStamped struct {
	Header Header
	Accel  Accel
}

func (m *AccelStamped) Type() ros.MessageType {
	return MsgAccelStamped
}

func (m *AccelStamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Accel
	if err = m.Accel.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Accel
	if err = m.Accel.Deserialize(buf); err != nil {
		return err
	}

	return
}
