// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//Point.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgPoint struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPoint) Text() string {
	return t.text
}

func (t *_MsgPoint) Name() string {
	return t.name
}

func (t *_MsgPoint) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPoint) NewMessage() ros.Message {
	m := new(Point)

	return m
}

var (
	MsgPoint = &_MsgPoint{
		`# This contains the position of a point in free space
float64 x
float64 y
float64 z
`,
		"geometry_msgs/Point",
		"243a4e5999bbb6bb311c053eea9e3ead",
	}
)

type Point struct {
	X float64
	Y float64
	Z float64
}

func (m *Point) Type() ros.MessageType {
	return MsgPoint
}

func (m *Point) Serialize(buf *bytes.Buffer) (err error) {
	// X
	binary.Write(buf, binary.LittleEndian, m.X)

	// Y
	binary.Write(buf, binary.LittleEndian, m.Y)

	// Z
	binary.Write(buf, binary.LittleEndian, m.Z)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// X
	if err = binary.Read(buf, binary.LittleEndian, &m.X); err != nil {
		return err
	}

	// Y
	if err = binary.Read(buf, binary.LittleEndian, &m.Y); err != nil {
		return err
	}

	// Z
	if err = binary.Read(buf, binary.LittleEndian, &m.Z); err != nil {
		return err
	}

	return
}
