// Code generated by ros-gen-go.
// source: Point32.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgPoint32 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPoint32) Text() string {
	return t.text
}

func (t *_MsgPoint32) Name() string {
	return t.name
}

func (t *_MsgPoint32) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPoint32) NewMessage() ros.Message {
	m := new(Point32)

	return m
}

var (
	MsgPoint32 = &_MsgPoint32{
		`# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z`,
		"geometry_msgs/Point32",
		"5513f8375d33dd96e850d3906e193f4a",
	}
)

type Point32 struct {
	X float32
	Y float32
	Z float32
}

func (m *Point32) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "float32", &m.X); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Y); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Z); err != nil {
		return err
	}

	return
}

func (m *Point32) Deserialize(r io.Reader) (err error) {
	// X
	if err = ros.DeserializeMessageField(r, "float32", &m.X); err != nil {
		return err
	}

	// Y
	if err = ros.DeserializeMessageField(r, "float32", &m.Y); err != nil {
		return err
	}

	// Z
	if err = ros.DeserializeMessageField(r, "float32", &m.Z); err != nil {
		return err
	}

	return
}
