// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//PolygonStamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgPolygonStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPolygonStamped) Text() string {
	return t.text
}

func (t *_MsgPolygonStamped) Name() string {
	return t.name
}

func (t *_MsgPolygonStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPolygonStamped) NewMessage() ros.Message {
	m := new(PolygonStamped)

	return m
}

var (
	MsgPolygonStamped = &_MsgPolygonStamped{
		`# This represents a Polygon with reference coordinate frame and timestamp
Header header
Polygon polygon
`,
		"geometry_msgs/PolygonStamped",
		"aa0712e581b3057dba582c695ff17d61",
	}
)

type PolygonStamped struct {
	Header  Header
	Polygon Polygon
}

func (m *PolygonStamped) Type() ros.MessageType {
	return MsgPolygonStamped
}

func (m *PolygonStamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Polygon
	if err = m.Polygon.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Polygon
	if err = m.Polygon.Deserialize(buf); err != nil {
		return err
	}

	return
}
