// Code generated by ros-gen-go.
// source: Pose2D.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgPose2D struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPose2D) Text() string {
	return t.text
}

func (t *_MsgPose2D) Name() string {
	return t.name
}

func (t *_MsgPose2D) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPose2D) NewMessage() ros.Message {
	m := new(Pose2D)

	return m
}

var (
	MsgPose2D = &_MsgPose2D{
		`# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta`,
		"geometry_msgs/Pose2D",
		"4e2f3fce2333423b30f6af38b9f2abd7",
	}
)

type Pose2D struct {
	X     float64
	Y     float64
	Theta float64
}

func (m *Pose2D) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "float64", &m.X); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Y); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Theta); err != nil {
		return err
	}

	return
}

func (m *Pose2D) Deserialize(r io.Reader) (err error) {
	// X
	if err = ros.DeserializeMessageField(r, "float64", &m.X); err != nil {
		return err
	}

	// Y
	if err = ros.DeserializeMessageField(r, "float64", &m.Y); err != nil {
		return err
	}

	// Theta
	if err = ros.DeserializeMessageField(r, "float64", &m.Theta); err != nil {
		return err
	}

	return
}
