// Code generated by ros-gen-go.
// source: PoseStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgPoseStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPoseStamped) Text() string {
	return t.text
}

func (t *_MsgPoseStamped) Name() string {
	return t.name
}

func (t *_MsgPoseStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPoseStamped) NewMessage() ros.Message {
	m := new(PoseStamped)

	return m
}

var (
	MsgPoseStamped = &_MsgPoseStamped{
		`# A Pose with reference coordinate frame and timestamp
Header header
Pose pose
`,
		"geometry_msgs/PoseStamped",
		"43f3760283d49766c9fdd69c4461f732",
	}
)

type PoseStamped struct {
	Header std_msgs.Header
	Pose   Pose
}

func (m *PoseStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "Pose", &m.Pose); err != nil {
		return err
	}

	return
}

func (m *PoseStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Pose
	if err = ros.DeserializeMessageField(r, "Pose", &m.Pose); err != nil {
		return err
	}

	return
}
