// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//PoseStamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgPoseStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPoseStamped) Text() string {
	return t.text
}

func (t *_MsgPoseStamped) Name() string {
	return t.name
}

func (t *_MsgPoseStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPoseStamped) NewMessage() ros.Message {
	m := new(PoseStamped)

	return m
}

var (
	MsgPoseStamped = &_MsgPoseStamped{
		`# A Pose with reference coordinate frame and timestamp
Header header
Pose pose
`,
		"geometry_msgs/PoseStamped",
		"43f3760283d49766c9fdd69c4461f732",
	}
)

type PoseStamped struct {
	Header Header
	Pose   Pose
}

func (m *PoseStamped) Type() ros.MessageType {
	return MsgPoseStamped
}

func (m *PoseStamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Pose
	if err = m.Pose.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Pose
	if err = m.Pose.Deserialize(buf); err != nil {
		return err
	}

	return
}
