// Code generated by ros-gen-go.
// source: PoseWithCovarianceStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgPoseWithCovarianceStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPoseWithCovarianceStamped) Text() string {
	return t.text
}

func (t *_MsgPoseWithCovarianceStamped) Name() string {
	return t.name
}

func (t *_MsgPoseWithCovarianceStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPoseWithCovarianceStamped) NewMessage() ros.Message {
	m := new(PoseWithCovarianceStamped)

	return m
}

var (
	MsgPoseWithCovarianceStamped = &_MsgPoseWithCovarianceStamped{
		`# This expresses an estimated pose with a reference coordinate frame and timestamp

Header header
PoseWithCovariance pose
`,
		"geometry_msgs/PoseWithCovarianceStamped",
		"729039794eaab042b403222dbf81e197",
	}
)

type PoseWithCovarianceStamped struct {
	Header std_msgs.Header
	Pose   PoseWithCovariance
}

func (m *PoseWithCovarianceStamped) Type() ros.MessageType {
	return MsgPoseWithCovarianceStamped
}

func (m *PoseWithCovarianceStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "PoseWithCovariance", &m.Pose); err != nil {
		return err
	}

	return
}

func (m *PoseWithCovarianceStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Pose
	if err = ros.DeserializeMessageField(r, "PoseWithCovariance", &m.Pose); err != nil {
		return err
	}

	return
}
