// Code generated by ros-gen-go.
// source: QuaternionStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgQuaternionStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgQuaternionStamped) Text() string {
	return t.text
}

func (t *_MsgQuaternionStamped) Name() string {
	return t.name
}

func (t *_MsgQuaternionStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgQuaternionStamped) NewMessage() ros.Message {
	m := new(QuaternionStamped)

	return m
}

var (
	MsgQuaternionStamped = &_MsgQuaternionStamped{
		`# This represents an orientation with reference coordinate frame and timestamp.

Header header
Quaternion quaternion
`,
		"geometry_msgs/QuaternionStamped",
		"4a5c00199247da86fc3d583bf5af5ca6",
	}
)

type QuaternionStamped struct {
	Header     std_msgs.Header
	Quaternion Quaternion
}

func (m *QuaternionStamped) Type() ros.MessageType {
	return MsgQuaternionStamped
}

func (m *QuaternionStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "Quaternion", &m.Quaternion); err != nil {
		return err
	}

	return
}

func (m *QuaternionStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Quaternion
	if err = ros.DeserializeMessageField(r, "Quaternion", &m.Quaternion); err != nil {
		return err
	}

	return
}
