// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//TwistStamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgTwistStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgTwistStamped) Text() string {
	return t.text
}

func (t *_MsgTwistStamped) Name() string {
	return t.name
}

func (t *_MsgTwistStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgTwistStamped) NewMessage() ros.Message {
	m := new(TwistStamped)

	return m
}

var (
	MsgTwistStamped = &_MsgTwistStamped{
		`# A twist with reference coordinate frame and timestamp
Header header
Twist twist
`,
		"geometry_msgs/TwistStamped",
		"08a22ddf566b82f747df9cc6e2fbbf7a",
	}
)

type TwistStamped struct {
	Header Header
	Twist  Twist
}

func (m *TwistStamped) Type() ros.MessageType {
	return MsgTwistStamped
}

func (m *TwistStamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Twist
	if err = m.Twist.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Twist
	if err = m.Twist.Deserialize(buf); err != nil {
		return err
	}

	return
}
