// Code generated by ros-gen-go.
// source: TwistWithCovariance.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"
	"encoding/binary"
	"fmt"

	"github.com/ppg/rosgo/ros"
)

type _MsgTwistWithCovariance struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgTwistWithCovariance) Text() string {
	return t.text
}

func (t *_MsgTwistWithCovariance) Name() string {
	return t.name
}

func (t *_MsgTwistWithCovariance) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgTwistWithCovariance) NewMessage() ros.Message {
	m := new(TwistWithCovariance)

	return m
}

var (
	MsgTwistWithCovariance = &_MsgTwistWithCovariance{
		`# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance
`,
		"geometry_msgs/TwistWithCovariance",
		"408e7ef4f4ec295f4663586922faacdd",
	}
)

type TwistWithCovariance struct {
	Twist      Twist
	Covariance [36]float64
}

func (m *TwistWithCovariance) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Twist", &m.Twist); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Covariance)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Covariance {
		if err = ros.SerializeMessageField(w, "float64", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *TwistWithCovariance) Deserialize(r io.Reader) (err error) {
	// Twist
	if err = ros.DeserializeMessageField(r, "Twist", &m.Twist); err != nil {
		return err
	}

	// Covariance
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Covariance: %s", err)
		}
		if size > 36 {
			return fmt.Errorf("array size for Covariance too large: expected=36, got=%d", size)
		}
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "float64", &m.Covariance[i]); err != nil {
				return err
			}
		}
	}

	return
}
