// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//Vector3Stamped.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgVector3Stamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgVector3Stamped) Text() string {
	return t.text
}

func (t *_MsgVector3Stamped) Name() string {
	return t.name
}

func (t *_MsgVector3Stamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgVector3Stamped) NewMessage() ros.Message {
	m := new(Vector3Stamped)

	return m
}

var (
	MsgVector3Stamped = &_MsgVector3Stamped{
		`# This represents a Vector3 with reference coordinate frame and timestamp
Header header
Vector3 vector
`,
		"geometry_msgs/Vector3Stamped",
		"25a0f208694a205ef85c426c089ebf78",
	}
)

type Vector3Stamped struct {
	Header Header
	Vector Vector3
}

func (m *Vector3Stamped) Type() ros.MessageType {
	return MsgVector3Stamped
}

func (m *Vector3Stamped) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Vector
	if err = m.Vector.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Vector
	if err = m.Vector.Deserialize(buf); err != nil {
		return err
	}

	return
}
