// Code generated by ros-gen-go.
// source: Vector3.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgVector3 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgVector3) Text() string {
	return t.text
}

func (t *_MsgVector3) Name() string {
	return t.name
}

func (t *_MsgVector3) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgVector3) NewMessage() ros.Message {
	m := new(Vector3)

	return m
}

var (
	MsgVector3 = &_MsgVector3{
		`# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z`,
		"geometry_msgs/Vector3",
		"a661f98e90ac456f3b4330d93aa5ae7e",
	}
)

type Vector3 struct {
	X float64
	Y float64
	Z float64
}

func (m *Vector3) Type() ros.MessageType {
	return MsgVector3
}

func (m *Vector3) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "float64", &m.X); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Y); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Z); err != nil {
		return err
	}

	return
}

func (m *Vector3) Deserialize(r io.Reader) (err error) {
	// X
	if err = ros.DeserializeMessageField(r, "float64", &m.X); err != nil {
		return err
	}

	// Y
	if err = ros.DeserializeMessageField(r, "float64", &m.Y); err != nil {
		return err
	}

	// Z
	if err = ros.DeserializeMessageField(r, "float64", &m.Z); err != nil {
		return err
	}

	return
}
