// Code generated by ros-gen-go.
// source: WrenchStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgWrenchStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgWrenchStamped) Text() string {
	return t.text
}

func (t *_MsgWrenchStamped) Name() string {
	return t.name
}

func (t *_MsgWrenchStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgWrenchStamped) NewMessage() ros.Message {
	m := new(WrenchStamped)

	return m
}

var (
	MsgWrenchStamped = &_MsgWrenchStamped{
		`# A wrench with reference coordinate frame and timestamp
Header header
Wrench wrench
`,
		"geometry_msgs/WrenchStamped",
		"150502b356390fb151385ef7647f633e",
	}
)

type WrenchStamped struct {
	Header std_msgs.Header
	Wrench Wrench
}

func (m *WrenchStamped) Type() ros.MessageType {
	return MsgWrenchStamped
}

func (m *WrenchStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "Wrench", &m.Wrench); err != nil {
		return err
	}

	return
}

func (m *WrenchStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Wrench
	if err = ros.DeserializeMessageField(r, "Wrench", &m.Wrench); err != nil {
		return err
	}

	return
}
