// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../geometry_msgs/msg//Wrench.msg
// DO NOT EDIT!
package geometry_msgs

type _MsgWrench struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgWrench) Text() string {
	return t.text
}

func (t *_MsgWrench) Name() string {
	return t.name
}

func (t *_MsgWrench) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgWrench) NewMessage() ros.Message {
	m := new(Wrench)

	return m
}

var (
	MsgWrench = &_MsgWrench{
		`# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque
`,
		"geometry_msgs/Wrench",
		"2aae87faaa553ae28e07e684016d765c",
	}
)

type Wrench struct {
	Force  Vector3
	Torque Vector3
}

func (m *Wrench) Type() ros.MessageType {
	return MsgWrench
}

func (m *Wrench) Serialize(buf *bytes.Buffer) (err error) {
	// Force
	if err = m.Force.Serialize(buf); err != nil {
		return err
	}

	// Torque
	if err = m.Torque.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Force
	if err = m.Force.Deserialize(buf); err != nil {
		return err
	}

	// Torque
	if err = m.Torque.Deserialize(buf); err != nil {
		return err
	}

	return
}
