// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Bool.msg
// DO NOT EDIT!
package std_msgs

type _MsgBool struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgBool) Text() string {
	return t.text
}

func (t *_MsgBool) Name() string {
	return t.name
}

func (t *_MsgBool) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgBool) NewMessage() ros.Message {
	m := new(Bool)

	return m
}

var (
	MsgBool = &_MsgBool{
		`bool data`,
		"std_msgs/Bool",
		"8b94c1b53db61fb6aed406028ad6332a",
	}
)

type Bool struct {
	Data bool
}

func (m *Bool) Type() ros.MessageType {
	return MsgBool
}

func (m *Bool) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
