// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Empty.msg
// DO NOT EDIT!
package std_msgs

type _MsgEmpty struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgEmpty) Text() string {
	return t.text
}

func (t *_MsgEmpty) Name() string {
	return t.name
}

func (t *_MsgEmpty) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgEmpty) NewMessage() ros.Message {
	m := new(Empty)

	return m
}

var (
	MsgEmpty = &_MsgEmpty{
		``,
		"std_msgs/Empty",
		"d41d8cd98f00b204e9800998ecf8427e",
	}
)

type Empty struct {
}

func (m *Empty) Type() ros.MessageType {
	return MsgEmpty
}

func (m *Empty) Serialize(buf *bytes.Buffer) (err error) {
	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	return
}
