// Code generated by ros-gen-go.
// source: Float64MultiArray.msg
// DO NOT EDIT!
package std_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgFloat64MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFloat64MultiArray) Text() string {
	return t.text
}

func (t *_MsgFloat64MultiArray) Name() string {
	return t.name
}

func (t *_MsgFloat64MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFloat64MultiArray) NewMessage() ros.Message {
	m := new(Float64MultiArray)

	return m
}

var (
	MsgFloat64MultiArray = &_MsgFloat64MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float64[]         data          # array of data

`,
		"std_msgs/Float64MultiArray",
		"91d9dc0a0be865cca07bcc646ba973d1",
	}
)

type Float64MultiArray struct {
	Layout MultiArrayLayout
	Data   []float64
}

func (m *Float64MultiArray) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "float64", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *Float64MultiArray) Deserialize(r io.Reader) (err error) {
	// Layout
	if err = ros.DeserializeMessageField(r, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Data
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Data: %s", err)
		}
		m.Data = make([]float64, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "float64", &m.Data[i]); err != nil {
				return err
			}
		}
	}

	return
}
