// Code generated by ros-gen-go.
// source: Float32MultiArray.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"
	"encoding/binary"
	"fmt"

	"github.com/ppg/rosgo/ros"
)

type _MsgFloat32MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFloat32MultiArray) Text() string {
	return t.text
}

func (t *_MsgFloat32MultiArray) Name() string {
	return t.name
}

func (t *_MsgFloat32MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFloat32MultiArray) NewMessage() ros.Message {
	m := new(Float32MultiArray)

	return m
}

var (
	MsgFloat32MultiArray = &_MsgFloat32MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float32[]         data          # array of data

`,
		"std_msgs/Float32MultiArray",
		"ff660c8bfaa6212a1286f181d2600631",
	}
)

type Float32MultiArray struct {
	Layout MultiArrayLayout
	Data   []float32
}

func (m *Float32MultiArray) Type() ros.MessageType {
	return MsgFloat32MultiArray
}

func (m *Float32MultiArray) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "float32", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *Float32MultiArray) Deserialize(r io.Reader) (err error) {
	// Layout
	if err = ros.DeserializeMessageField(r, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Data
	// Read size little endian
	var size uint32
	if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
		return fmt.Errorf("cannot read array size for Data: %s", err)
	}
	m.Data = make([]float32, int(size))
	for i := 0; i < int(size); i++ {
		if err = ros.DeserializeMessageField(r, "float32", &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
