// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Float32MultiArray.msg
// DO NOT EDIT!
package std_msgs

type _MsgFloat32MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFloat32MultiArray) Text() string {
	return t.text
}

func (t *_MsgFloat32MultiArray) Name() string {
	return t.name
}

func (t *_MsgFloat32MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFloat32MultiArray) NewMessage() ros.Message {
	m := new(Float32MultiArray)

	return m
}

var (
	MsgFloat32MultiArray = &_MsgFloat32MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float32[]         data          # array of data

`,
		"std_msgs/Float32MultiArray",
		"ff660c8bfaa6212a1286f181d2600631",
	}
)

type Float32MultiArray struct {
	Layout MultiArrayLayout
	Data   []float32
}

func (m *Float32MultiArray) Type() ros.MessageType {
	return MsgFloat32MultiArray
}

func (m *Float32MultiArray) Serialize(buf *bytes.Buffer) (err error) {
	// Layout
	if err = m.Layout.Serialize(buf); err != nil {
		return err
	}

	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Data)))
	for _, e := range m.Data {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Layout
	if err = m.Layout.Deserialize(buf); err != nil {
		return err
	}

	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Data = make([]float32, int(size))
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
