// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Float32.msg
// DO NOT EDIT!
package std_msgs

type _MsgFloat32 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFloat32) Text() string {
	return t.text
}

func (t *_MsgFloat32) Name() string {
	return t.name
}

func (t *_MsgFloat32) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFloat32) NewMessage() ros.Message {
	m := new(Float32)

	return m
}

var (
	MsgFloat32 = &_MsgFloat32{
		`float32 data`,
		"std_msgs/Float32",
		"73fcbf46b49191e672908e50842a83d4",
	}
)

type Float32 struct {
	Data float32
}

func (m *Float32) Type() ros.MessageType {
	return MsgFloat32
}

func (m *Float32) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
