// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Float64MultiArray.msg
// DO NOT EDIT!
package std_msgs

type _MsgFloat64MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFloat64MultiArray) Text() string {
	return t.text
}

func (t *_MsgFloat64MultiArray) Name() string {
	return t.name
}

func (t *_MsgFloat64MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFloat64MultiArray) NewMessage() ros.Message {
	m := new(Float64MultiArray)

	return m
}

var (
	MsgFloat64MultiArray = &_MsgFloat64MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float64[]         data          # array of data

`,
		"std_msgs/Float64MultiArray",
		"91d9dc0a0be865cca07bcc646ba973d1",
	}
)

type Float64MultiArray struct {
	Layout MultiArrayLayout
	Data   []float64
}

func (m *Float64MultiArray) Type() ros.MessageType {
	return MsgFloat64MultiArray
}

func (m *Float64MultiArray) Serialize(buf *bytes.Buffer) (err error) {
	// Layout
	if err = m.Layout.Serialize(buf); err != nil {
		return err
	}

	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Data)))
	for _, e := range m.Data {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Layout
	if err = m.Layout.Deserialize(buf); err != nil {
		return err
	}

	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Data = make([]float64, int(size))
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
