// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Header.msg
// DO NOT EDIT!
package std_msgs

type _MsgHeader struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgHeader) Text() string {
	return t.text
}

func (t *_MsgHeader) Name() string {
	return t.name
}

func (t *_MsgHeader) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgHeader) NewMessage() ros.Message {
	m := new(Header)

	return m
}

var (
	MsgHeader = &_MsgHeader{
		`# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
`,
		"std_msgs/Header",
		"b570e0075f4022ff277e41bba54229f5",
	}
)

type Header struct {
	Seq     uint32
	Stamp   ros.Time
	FrameID string
}

func (m *Header) Type() ros.MessageType {
	return MsgHeader
}

func (m *Header) Serialize(buf *bytes.Buffer) (err error) {
	// Seq
	binary.Write(buf, binary.LittleEndian, m.Seq)

	// Stamp
	binary.Write(buf, binary.LittleEndian, m.Stamp.Sec)
	binary.Write(buf, binary.LittleEndian, m.Stamp.NSec)

	// FrameID
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.FrameID))))
	buf.Write([]byte(m.FrameID))

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Seq
	if err = binary.Read(buf, binary.LittleEndian, &m.Seq); err != nil {
		return err
	}

	// Stamp
	if err = binary.Read(buf, binary.LittleEndian, &m.Stamp.Sec); err != nil {
		return err
	}
	if err = binary.Read(buf, binary.LittleEndian, &m.Stamp.NSec); err != nil {
		return err
	}

	// FrameID
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	data := make([]byte, int(size))
	if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
		return err
	}
	m.FrameID = string(data)

	return
}
