// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Int16.msg
// DO NOT EDIT!
package std_msgs

type _MsgInt16 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt16) Text() string {
	return t.text
}

func (t *_MsgInt16) Name() string {
	return t.name
}

func (t *_MsgInt16) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt16) NewMessage() ros.Message {
	m := new(Int16)

	return m
}

var (
	MsgInt16 = &_MsgInt16{
		`int16 data
`,
		"std_msgs/Int16",
		"e89cc27b8d0ebcac7830e5a6e447f615",
	}
)

type Int16 struct {
	Data int16
}

func (m *Int16) Type() ros.MessageType {
	return MsgInt16
}

func (m *Int16) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
