// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Int16MultiArray.msg
// DO NOT EDIT!
package std_msgs

type _MsgInt16MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt16MultiArray) Text() string {
	return t.text
}

func (t *_MsgInt16MultiArray) Name() string {
	return t.name
}

func (t *_MsgInt16MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt16MultiArray) NewMessage() ros.Message {
	m := new(Int16MultiArray)

	return m
}

var (
	MsgInt16MultiArray = &_MsgInt16MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
int16[]           data          # array of data

`,
		"std_msgs/Int16MultiArray",
		"1ea95620317e8e06fc1614473147a513",
	}
)

type Int16MultiArray struct {
	Layout MultiArrayLayout
	Data   []int16
}

func (m *Int16MultiArray) Type() ros.MessageType {
	return MsgInt16MultiArray
}

func (m *Int16MultiArray) Serialize(buf *bytes.Buffer) (err error) {
	// Layout
	if err = m.Layout.Serialize(buf); err != nil {
		return err
	}

	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Data)))
	for _, e := range m.Data {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Layout
	if err = m.Layout.Deserialize(buf); err != nil {
		return err
	}

	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Data = make([]int16, int(size))
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
