// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Int32MultiArray.msg
// DO NOT EDIT!
package std_msgs

type _MsgInt32MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt32MultiArray) Text() string {
	return t.text
}

func (t *_MsgInt32MultiArray) Name() string {
	return t.name
}

func (t *_MsgInt32MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt32MultiArray) NewMessage() ros.Message {
	m := new(Int32MultiArray)

	return m
}

var (
	MsgInt32MultiArray = &_MsgInt32MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
int32[]           data          # array of data

`,
		"std_msgs/Int32MultiArray",
		"0d0e27a7e8bf5340e47bbe4fcde637f2",
	}
)

type Int32MultiArray struct {
	Layout MultiArrayLayout
	Data   []int32
}

func (m *Int32MultiArray) Type() ros.MessageType {
	return MsgInt32MultiArray
}

func (m *Int32MultiArray) Serialize(buf *bytes.Buffer) (err error) {
	// Layout
	if err = m.Layout.Serialize(buf); err != nil {
		return err
	}

	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Data)))
	for _, e := range m.Data {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Layout
	if err = m.Layout.Deserialize(buf); err != nil {
		return err
	}

	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Data = make([]int32, int(size))
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
