// Code generated by ros-gen-go.
// source: Int64.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgInt64 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt64) Text() string {
	return t.text
}

func (t *_MsgInt64) Name() string {
	return t.name
}

func (t *_MsgInt64) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt64) NewMessage() ros.Message {
	m := new(Int64)

	return m
}

var (
	MsgInt64 = &_MsgInt64{
		`int64 data`,
		"std_msgs/Int64",
		"34add168574510e6e17f5d23ecc077ef",
	}
)

type Int64 struct {
	Data int64
}

func (m *Int64) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "int64", &m.Data); err != nil {
		return err
	}

	return
}

func (m *Int64) Deserialize(r io.Reader) (err error) {
	// Data
	if err = ros.DeserializeMessageField(r, "int64", &m.Data); err != nil {
		return err
	}

	return
}
