// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Int64.msg
// DO NOT EDIT!
package std_msgs

type _MsgInt64 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt64) Text() string {
	return t.text
}

func (t *_MsgInt64) Name() string {
	return t.name
}

func (t *_MsgInt64) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt64) NewMessage() ros.Message {
	m := new(Int64)

	return m
}

var (
	MsgInt64 = &_MsgInt64{
		`int64 data`,
		"std_msgs/Int64",
		"34add168574510e6e17f5d23ecc077ef",
	}
)

type Int64 struct {
	Data int64
}

func (m *Int64) Type() ros.MessageType {
	return MsgInt64
}

func (m *Int64) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
