// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Int8MultiArray.msg
// DO NOT EDIT!
package std_msgs

type _MsgInt8MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgInt8MultiArray) Text() string {
	return t.text
}

func (t *_MsgInt8MultiArray) Name() string {
	return t.name
}

func (t *_MsgInt8MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgInt8MultiArray) NewMessage() ros.Message {
	m := new(Int8MultiArray)

	return m
}

var (
	MsgInt8MultiArray = &_MsgInt8MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
int8[]            data          # array of data

`,
		"std_msgs/Int8MultiArray",
		"702d1af09e8cdff126b1181fd8ce30b3",
	}
)

type Int8MultiArray struct {
	Layout MultiArrayLayout
	Data   []int8
}

func (m *Int8MultiArray) Type() ros.MessageType {
	return MsgInt8MultiArray
}

func (m *Int8MultiArray) Serialize(buf *bytes.Buffer) (err error) {
	// Layout
	if err = m.Layout.Serialize(buf); err != nil {
		return err
	}

	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Data)))
	for _, e := range m.Data {
		binary.Write(buf, binary.LittleEndian, e)
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Layout
	if err = m.Layout.Deserialize(buf); err != nil {
		return err
	}

	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Data = make([]int8, int(size))
	for i := 0; i < int(size); i++ {
		if err = binary.Read(buf, binary.LittleEndian, &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
