// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//MultiArrayDimension.msg
// DO NOT EDIT!
package std_msgs

type _MsgMultiArrayDimension struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgMultiArrayDimension) Text() string {
	return t.text
}

func (t *_MsgMultiArrayDimension) Name() string {
	return t.name
}

func (t *_MsgMultiArrayDimension) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgMultiArrayDimension) NewMessage() ros.Message {
	m := new(MultiArrayDimension)

	return m
}

var (
	MsgMultiArrayDimension = &_MsgMultiArrayDimension{
		`string label   # label of given dimension
uint32 size    # size of given dimension (in type units)
uint32 stride  # stride of given dimension`,
		"std_msgs/MultiArrayDimension",
		"b8e7d500a9ab625aab96d646720abb13",
	}
)

type MultiArrayDimension struct {
	Label  string
	Size   uint32
	Stride uint32
}

func (m *MultiArrayDimension) Type() ros.MessageType {
	return MsgMultiArrayDimension
}

func (m *MultiArrayDimension) Serialize(buf *bytes.Buffer) (err error) {
	// Label
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.Label))))
	buf.Write([]byte(m.Label))

	// Size
	binary.Write(buf, binary.LittleEndian, m.Size)

	// Stride
	binary.Write(buf, binary.LittleEndian, m.Stride)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Label
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	data := make([]byte, int(size))
	if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
		return err
	}
	m.Label = string(data)

	// Size
	if err = binary.Read(buf, binary.LittleEndian, &m.Size); err != nil {
		return err
	}

	// Stride
	if err = binary.Read(buf, binary.LittleEndian, &m.Stride); err != nil {
		return err
	}

	return
}
