// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//String.msg
// DO NOT EDIT!
package std_msgs

type _MsgString struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgString) Text() string {
	return t.text
}

func (t *_MsgString) Name() string {
	return t.name
}

func (t *_MsgString) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgString) NewMessage() ros.Message {
	m := new(String)

	return m
}

var (
	MsgString = &_MsgString{
		`string data
`,
		"std_msgs/String",
		"5b89344b4d080ca499c0648063c40738",
	}
)

type String struct {
	Data string
}

func (m *String) Type() ros.MessageType {
	return MsgString
}

func (m *String) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.Data))))
	buf.Write([]byte(m.Data))

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	data := make([]byte, int(size))
	if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
		return err
	}
	m.Data = string(data)

	return
}
