// Code generated by ros-gen-go.
// source: String.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgString struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgString) Text() string {
	return t.text
}

func (t *_MsgString) Name() string {
	return t.name
}

func (t *_MsgString) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgString) NewMessage() ros.Message {
	m := new(String)

	return m
}

var (
	MsgString = &_MsgString{
		`string data
`,
		"std_msgs/String",
		"5b89344b4d080ca499c0648063c40738",
	}
)

type String struct {
	Data string
}

func (m *String) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.Data); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(r io.Reader) (err error) {
	// Data
	if err = ros.DeserializeMessageField(r, "string", &m.Data); err != nil {
		return err
	}

	return
}
