// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//Time.msg
// DO NOT EDIT!
package std_msgs

type _MsgTime struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgTime) Text() string {
	return t.text
}

func (t *_MsgTime) Name() string {
	return t.name
}

func (t *_MsgTime) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgTime) NewMessage() ros.Message {
	m := new(Time)

	return m
}

var (
	MsgTime = &_MsgTime{
		`time data
`,
		"std_msgs/Time",
		"04996afd7481fbeb7a3cfac675a5f3a3",
	}
)

type Time struct {
	Data ros.Time
}

func (m *Time) Type() ros.MessageType {
	return MsgTime
}

func (m *Time) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data.Sec)
	binary.Write(buf, binary.LittleEndian, m.Data.NSec)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data.Sec); err != nil {
		return err
	}
	if err = binary.Read(buf, binary.LittleEndian, &m.Data.NSec); err != nil {
		return err
	}

	return
}
