// Code generated by ros-gen-go.
// source: UInt8MultiArray.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"
	"encoding/binary"
	"fmt"

	"github.com/ppg/rosgo/ros"
)

type _MsgUInt8MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt8MultiArray) Text() string {
	return t.text
}

func (t *_MsgUInt8MultiArray) Name() string {
	return t.name
}

func (t *_MsgUInt8MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt8MultiArray) NewMessage() ros.Message {
	m := new(UInt8MultiArray)

	return m
}

var (
	MsgUInt8MultiArray = &_MsgUInt8MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
uint8[]           data          # array of data

`,
		"std_msgs/UInt8MultiArray",
		"f4e8b0b29fb299bd0cc3a9314fe2f425",
	}
)

type UInt8MultiArray struct {
	Layout MultiArrayLayout
	Data   []uint8
}

func (m *UInt8MultiArray) Type() ros.MessageType {
	return MsgUInt8MultiArray
}

func (m *UInt8MultiArray) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "uint8", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *UInt8MultiArray) Deserialize(r io.Reader) (err error) {
	// Layout
	if err = ros.DeserializeMessageField(r, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Data
	// Read size little endian
	var size uint32
	if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
		return fmt.Errorf("cannot read array size for Data: %s", err)
	}
	m.Data = make([]uint8, int(size))
	for i := 0; i < int(size); i++ {
		if err = ros.DeserializeMessageField(r, "uint8", &m.Data[i]); err != nil {
			return err
		}
	}

	return
}
