// Code generated by ros-gen-go.
// source: UInt32.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgUInt32 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt32) Text() string {
	return t.text
}

func (t *_MsgUInt32) Name() string {
	return t.name
}

func (t *_MsgUInt32) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt32) NewMessage() ros.Message {
	m := new(UInt32)

	return m
}

var (
	MsgUInt32 = &_MsgUInt32{
		`uint32 data`,
		"std_msgs/UInt32",
		"304a39449588c7f8ce2df6e8001c5fce",
	}
)

type UInt32 struct {
	Data uint32
}

func (m *UInt32) Type() ros.MessageType {
	return MsgUInt32
}

func (m *UInt32) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "uint32", &m.Data); err != nil {
		return err
	}

	return
}

func (m *UInt32) Deserialize(r io.Reader) (err error) {
	// Data
	if err = ros.DeserializeMessageField(r, "uint32", &m.Data); err != nil {
		return err
	}

	return
}
