// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//UInt8.msg
// DO NOT EDIT!
package std_msgs

type _MsgUInt8 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt8) Text() string {
	return t.text
}

func (t *_MsgUInt8) Name() string {
	return t.name
}

func (t *_MsgUInt8) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt8) NewMessage() ros.Message {
	m := new(UInt8)

	return m
}

var (
	MsgUInt8 = &_MsgUInt8{
		`uint8 data
`,
		"std_msgs/UInt8",
		"7dd4c5dca2bc8c0277734d2bba45f965",
	}
)

type UInt8 struct {
	Data uint8
}

func (m *UInt8) Type() ros.MessageType {
	return MsgUInt8
}

func (m *UInt8) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
