// Code generated by ros-gen-go.
// source: UInt16MultiArray.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"
	"encoding/binary"
	"fmt"

	"github.com/ppg/rosgo/ros"
)

type _MsgUInt16MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt16MultiArray) Text() string {
	return t.text
}

func (t *_MsgUInt16MultiArray) Name() string {
	return t.name
}

func (t *_MsgUInt16MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt16MultiArray) NewMessage() ros.Message {
	m := new(UInt16MultiArray)

	return m
}

var (
	MsgUInt16MultiArray = &_MsgUInt16MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
uint16[]            data        # array of data

`,
		"std_msgs/UInt16MultiArray",
		"f4afccd5ed018fe68096c8366280b959",
	}
)

type UInt16MultiArray struct {
	Layout MultiArrayLayout
	Data   []uint16
}

func (m *UInt16MultiArray) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "uint16", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *UInt16MultiArray) Deserialize(r io.Reader) (err error) {
	// Layout
	if err = ros.DeserializeMessageField(r, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Data
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Data: %s", err)
		}
		m.Data = make([]uint16, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "uint16", &m.Data[i]); err != nil {
				return err
			}
		}
	}

	return
}
