// Code generated by ros-gen-go.
// source: UInt32MultiArray.msg
// DO NOT EDIT!
package std_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgUInt32MultiArray struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt32MultiArray) Text() string {
	return t.text
}

func (t *_MsgUInt32MultiArray) Name() string {
	return t.name
}

func (t *_MsgUInt32MultiArray) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt32MultiArray) NewMessage() ros.Message {
	m := new(UInt32MultiArray)

	return m
}

var (
	MsgUInt32MultiArray = &_MsgUInt32MultiArray{
		`# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
uint32[]          data          # array of data

`,
		"std_msgs/UInt32MultiArray",
		"55400a29858f382b20e1982347702f45",
	}
)

type UInt32MultiArray struct {
	Layout MultiArrayLayout
	Data   []uint32
}

func (m *UInt32MultiArray) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "uint32", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *UInt32MultiArray) Deserialize(r io.Reader) (err error) {
	// Layout
	if err = ros.DeserializeMessageField(r, "MultiArrayLayout", &m.Layout); err != nil {
		return err
	}

	// Data
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Data: %s", err)
		}
		m.Data = make([]uint32, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "uint32", &m.Data[i]); err != nil {
				return err
			}
		}
	}

	return
}
