// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../std_msgs/msg//UInt64.msg
// DO NOT EDIT!
package std_msgs

type _MsgUInt64 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt64) Text() string {
	return t.text
}

func (t *_MsgUInt64) Name() string {
	return t.name
}

func (t *_MsgUInt64) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt64) NewMessage() ros.Message {
	m := new(UInt64)

	return m
}

var (
	MsgUInt64 = &_MsgUInt64{
		`uint64 data`,
		"std_msgs/UInt64",
		"1b2a79973e8bf53d7b53acb71299cb57",
	}
)

type UInt64 struct {
	Data uint64
}

func (m *UInt64) Type() ros.MessageType {
	return MsgUInt64
}

func (m *UInt64) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, m.Data)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	if err = binary.Read(buf, binary.LittleEndian, &m.Data); err != nil {
		return err
	}

	return
}
