// Code generated by ros-gen-go.
// source: UInt16.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgUInt16 struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgUInt16) Text() string {
	return t.text
}

func (t *_MsgUInt16) Name() string {
	return t.name
}

func (t *_MsgUInt16) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgUInt16) NewMessage() ros.Message {
	m := new(UInt16)

	return m
}

var (
	MsgUInt16 = &_MsgUInt16{
		`uint16 data
`,
		"std_msgs/UInt16",
		"fd863ad7ac309d337ff46193bc0af4c0",
	}
)

type UInt16 struct {
	Data uint16
}

func (m *UInt16) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "uint16", &m.Data); err != nil {
		return err
	}

	return
}

func (m *UInt16) Deserialize(r io.Reader) (err error) {
	// Data
	if err = ros.DeserializeMessageField(r, "uint16", &m.Data); err != nil {
		return err
	}

	return
}
