// Code generated by ros-gen-go.
// source: FollowJointTrajectoryActionFeedback.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgFollowJointTrajectoryActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryActionFeedback) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryActionFeedback) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryActionFeedback) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryActionFeedback)

	return m
}

var (
	MsgFollowJointTrajectoryActionFeedback = &_MsgFollowJointTrajectoryActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowJointTrajectoryFeedback feedback
`,
		"control_msgs/FollowJointTrajectoryActionFeedback",
		"25790fef5dd90a2c2ed3ad3832b1c3a4",
	}
)

type FollowJointTrajectoryActionFeedback struct {
	Header   std_msgs.Header
	Status   actionlib_msgs.GoalStatus
	Feedback FollowJointTrajectoryFeedback
}

func (m *FollowJointTrajectoryActionFeedback) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "FollowJointTrajectoryFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}

func (m *FollowJointTrajectoryActionFeedback) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Feedback
	if err = ros.DeserializeMessageField(r, "FollowJointTrajectoryFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}
