// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//FollowJointTrajectoryActionGoal.msg
// DO NOT EDIT!
package control_msgs

type _MsgFollowJointTrajectoryActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryActionGoal) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryActionGoal) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryActionGoal) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryActionGoal)

	return m
}

var (
	MsgFollowJointTrajectoryActionGoal = &_MsgFollowJointTrajectoryActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
FollowJointTrajectoryGoal goal
`,
		"control_msgs/FollowJointTrajectoryActionGoal",
		"ea97e347ff08322557a8ca22058939c7",
	}
)

type FollowJointTrajectoryActionGoal struct {
	Header Header
	GoalID actionlib_msgs.GoalID
	Goal   FollowJointTrajectoryGoal
}

func (m *FollowJointTrajectoryActionGoal) Type() ros.MessageType {
	return MsgFollowJointTrajectoryActionGoal
}

func (m *FollowJointTrajectoryActionGoal) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Serialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Deserialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}

	return
}
