// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//FollowJointTrajectoryActionFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgFollowJointTrajectoryActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryActionFeedback) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryActionFeedback) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryActionFeedback) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryActionFeedback)

	return m
}

var (
	MsgFollowJointTrajectoryActionFeedback = &_MsgFollowJointTrajectoryActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowJointTrajectoryFeedback feedback
`,
		"control_msgs/FollowJointTrajectoryActionFeedback",
		"25790fef5dd90a2c2ed3ad3832b1c3a4",
	}
)

type FollowJointTrajectoryActionFeedback struct {
	Header   Header
	Status   actionlib_msgs.GoalStatus
	Feedback FollowJointTrajectoryFeedback
}

func (m *FollowJointTrajectoryActionFeedback) Type() ros.MessageType {
	return MsgFollowJointTrajectoryActionFeedback
}

func (m *FollowJointTrajectoryActionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
