// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//FollowJointTrajectoryFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgFollowJointTrajectoryFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryFeedback) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryFeedback) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryFeedback) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryFeedback)

	return m
}

var (
	MsgFollowJointTrajectoryFeedback = &_MsgFollowJointTrajectoryFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
Header header
string[] joint_names
trajectory_msgs/JointTrajectoryPoint desired
trajectory_msgs/JointTrajectoryPoint actual
trajectory_msgs/JointTrajectoryPoint error

`,
		"control_msgs/FollowJointTrajectoryFeedback",
		"43a9ee5418d7d1b272026ea4d743553e",
	}
)

type FollowJointTrajectoryFeedback struct {
	Header     Header
	JointNames []string
	Desired    trajectory_msgs.JointTrajectoryPoint
	Actual     trajectory_msgs.JointTrajectoryPoint
	Error      trajectory_msgs.JointTrajectoryPoint
}

func (m *FollowJointTrajectoryFeedback) Type() ros.MessageType {
	return MsgFollowJointTrajectoryFeedback
}

func (m *FollowJointTrajectoryFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// JointNames
	binary.Write(buf, binary.LittleEndian, uint32(len(m.JointNames)))
	for _, e := range m.JointNames {
		binary.Write(buf, binary.LittleEndian, uint32(len([]byte(e))))
		buf.Write([]byte(e))
	}

	// Desired
	if err = m.Desired.Serialize(buf); err != nil {
		return err
	}

	// Actual
	if err = m.Actual.Serialize(buf); err != nil {
		return err
	}

	// Error
	if err = m.Error.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// JointNames
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.JointNames = make([]string, int(size))
	for i := 0; i < int(size); i++ {
		var size uint32
		if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
			return err
		}
		data := make([]byte, int(size))
		if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
			return err
		}
		m.JointNames[i] = string(data)
	}

	// Desired
	if err = m.Desired.Deserialize(buf); err != nil {
		return err
	}

	// Actual
	if err = m.Actual.Deserialize(buf); err != nil {
		return err
	}

	// Error
	if err = m.Error.Deserialize(buf); err != nil {
		return err
	}

	return
}
