// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//GripperCommandActionFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgGripperCommandActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandActionFeedback) Text() string {
	return t.text
}

func (t *_MsgGripperCommandActionFeedback) Name() string {
	return t.name
}

func (t *_MsgGripperCommandActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandActionFeedback) NewMessage() ros.Message {
	m := new(GripperCommandActionFeedback)

	return m
}

var (
	MsgGripperCommandActionFeedback = &_MsgGripperCommandActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GripperCommandFeedback feedback
`,
		"control_msgs/GripperCommandActionFeedback",
		"fe736ee47419d781e25d23721e3df6e5",
	}
)

type GripperCommandActionFeedback struct {
	Header   Header
	Status   actionlib_msgs.GoalStatus
	Feedback GripperCommandFeedback
}

func (m *GripperCommandActionFeedback) Type() ros.MessageType {
	return MsgGripperCommandActionFeedback
}

func (m *GripperCommandActionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
