// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//GripperCommandActionGoal.msg
// DO NOT EDIT!
package control_msgs

type _MsgGripperCommandActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandActionGoal) Text() string {
	return t.text
}

func (t *_MsgGripperCommandActionGoal) Name() string {
	return t.name
}

func (t *_MsgGripperCommandActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandActionGoal) NewMessage() ros.Message {
	m := new(GripperCommandActionGoal)

	return m
}

var (
	MsgGripperCommandActionGoal = &_MsgGripperCommandActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GripperCommandGoal goal
`,
		"control_msgs/GripperCommandActionGoal",
		"afbb0281892695d5519cbad8f2cc3fce",
	}
)

type GripperCommandActionGoal struct {
	Header Header
	GoalID actionlib_msgs.GoalID
	Goal   GripperCommandGoal
}

func (m *GripperCommandActionGoal) Type() ros.MessageType {
	return MsgGripperCommandActionGoal
}

func (m *GripperCommandActionGoal) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Serialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Deserialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}

	return
}
