// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//GripperCommandFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgGripperCommandFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandFeedback) Text() string {
	return t.text
}

func (t *_MsgGripperCommandFeedback) Name() string {
	return t.name
}

func (t *_MsgGripperCommandFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandFeedback) NewMessage() ros.Message {
	m := new(GripperCommandFeedback)

	return m
}

var (
	MsgGripperCommandFeedback = &_MsgGripperCommandFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 position  # The current gripper gap size (in meters)
float64 effort    # The current effort exerted (in Newtons)
bool stalled      # True iff the gripper is exerting max effort and not moving
bool reached_goal # True iff the gripper position has reached the commanded setpoint

`,
		"control_msgs/GripperCommandFeedback",
		"74f2b51f6c37d7f6d457ab6aa2205259",
	}
)

type GripperCommandFeedback struct {
	Position    float64
	Effort      float64
	Stalled     bool
	ReachedGoal bool
}

func (m *GripperCommandFeedback) Type() ros.MessageType {
	return MsgGripperCommandFeedback
}

func (m *GripperCommandFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Position
	binary.Write(buf, binary.LittleEndian, m.Position)

	// Effort
	binary.Write(buf, binary.LittleEndian, m.Effort)

	// Stalled
	binary.Write(buf, binary.LittleEndian, m.Stalled)

	// ReachedGoal
	binary.Write(buf, binary.LittleEndian, m.ReachedGoal)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Position
	if err = binary.Read(buf, binary.LittleEndian, &m.Position); err != nil {
		return err
	}

	// Effort
	if err = binary.Read(buf, binary.LittleEndian, &m.Effort); err != nil {
		return err
	}

	// Stalled
	if err = binary.Read(buf, binary.LittleEndian, &m.Stalled); err != nil {
		return err
	}

	// ReachedGoal
	if err = binary.Read(buf, binary.LittleEndian, &m.ReachedGoal); err != nil {
		return err
	}

	return
}
