// Code generated by ros-gen-go.
// source: GripperCommandActionFeedback.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
	"github.com/ppg/rosgo/ros"
)

type _MsgGripperCommandActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandActionFeedback) Text() string {
	return t.text
}

func (t *_MsgGripperCommandActionFeedback) Name() string {
	return t.name
}

func (t *_MsgGripperCommandActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandActionFeedback) NewMessage() ros.Message {
	m := new(GripperCommandActionFeedback)

	return m
}

var (
	MsgGripperCommandActionFeedback = &_MsgGripperCommandActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GripperCommandFeedback feedback
`,
		"control_msgs/GripperCommandActionFeedback",
		"fe736ee47419d781e25d23721e3df6e5",
	}
)

type GripperCommandActionFeedback struct {
	Header   std_msgs.Header
	Status   actionlib_msgs.GoalStatus
	Feedback GripperCommandFeedback
}

func (m *GripperCommandActionFeedback) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "GripperCommandFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}

func (m *GripperCommandActionFeedback) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Feedback
	if err = ros.DeserializeMessageField(r, "GripperCommandFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}
