// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//GripperCommandAction.msg
// DO NOT EDIT!
package control_msgs

type _MsgGripperCommandAction struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandAction) Text() string {
	return t.text
}

func (t *_MsgGripperCommandAction) Name() string {
	return t.name
}

func (t *_MsgGripperCommandAction) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandAction) NewMessage() ros.Message {
	m := new(GripperCommandAction)

	return m
}

var (
	MsgGripperCommandAction = &_MsgGripperCommandAction{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

GripperCommandActionGoal action_goal
GripperCommandActionResult action_result
GripperCommandActionFeedback action_feedback
`,
		"control_msgs/GripperCommandAction",
		"3c4beda8eaf53846fc63a79ab375a505",
	}
)

type GripperCommandAction struct {
	ActionGoal     GripperCommandActionGoal
	ActionResult   GripperCommandActionResult
	ActionFeedback GripperCommandActionFeedback
}

func (m *GripperCommandAction) Type() ros.MessageType {
	return MsgGripperCommandAction
}

func (m *GripperCommandAction) Serialize(buf *bytes.Buffer) (err error) {
	// ActionGoal
	if err = m.ActionGoal.Serialize(buf); err != nil {
		return err
	}

	// ActionResult
	if err = m.ActionResult.Serialize(buf); err != nil {
		return err
	}

	// ActionFeedback
	if err = m.ActionFeedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// ActionGoal
	if err = m.ActionGoal.Deserialize(buf); err != nil {
		return err
	}

	// ActionResult
	if err = m.ActionResult.Deserialize(buf); err != nil {
		return err
	}

	// ActionFeedback
	if err = m.ActionFeedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
