// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//JointTrajectoryActionGoal.msg
// DO NOT EDIT!
package control_msgs

type _MsgJointTrajectoryActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryActionGoal) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryActionGoal) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryActionGoal) NewMessage() ros.Message {
	m := new(JointTrajectoryActionGoal)

	return m
}

var (
	MsgJointTrajectoryActionGoal = &_MsgJointTrajectoryActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
JointTrajectoryGoal goal
`,
		"control_msgs/JointTrajectoryActionGoal",
		"8a6e281d5c8c3406156b0b6414c4cbe9",
	}
)

type JointTrajectoryActionGoal struct {
	Header Header
	GoalID actionlib_msgs.GoalID
	Goal   JointTrajectoryGoal
}

func (m *JointTrajectoryActionGoal) Type() ros.MessageType {
	return MsgJointTrajectoryActionGoal
}

func (m *JointTrajectoryActionGoal) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Serialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Deserialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}

	return
}
