// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//JointTrajectoryResult.msg
// DO NOT EDIT!
package control_msgs

type _MsgJointTrajectoryResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryResult) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryResult) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryResult) NewMessage() ros.Message {
	m := new(JointTrajectoryResult)

	return m
}

var (
	MsgJointTrajectoryResult = &_MsgJointTrajectoryResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
`,
		"control_msgs/JointTrajectoryResult",
		"7ac3b32c97133caf1b14edc99a50c37d",
	}
)

type JointTrajectoryResult struct {
}

func (m *JointTrajectoryResult) Type() ros.MessageType {
	return MsgJointTrajectoryResult
}

func (m *JointTrajectoryResult) Serialize(buf *bytes.Buffer) (err error) {
	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	return
}
