// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//JointControllerState.msg
// DO NOT EDIT!
package control_msgs

type _MsgJointControllerState struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointControllerState) Text() string {
	return t.text
}

func (t *_MsgJointControllerState) Name() string {
	return t.name
}

func (t *_MsgJointControllerState) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointControllerState) NewMessage() ros.Message {
	m := new(JointControllerState)

	return m
}

var (
	MsgJointControllerState = &_MsgJointControllerState{
		`Header header
float64 set_point
float64 process_value
float64 process_value_dot
float64 error
float64 time_step
float64 command
float64 p
float64 i
float64 d
float64 i_clamp

`,
		"control_msgs/JointControllerState",
		"8bdc19d6058e1654165f129c40b1bc86",
	}
)

type JointControllerState struct {
	Header          Header
	SetPoint        float64
	ProcessValue    float64
	ProcessValueDot float64
	Error           float64
	TimeStep        float64
	Command         float64
	P               float64
	I               float64
	D               float64
	IClamp          float64
}

func (m *JointControllerState) Type() ros.MessageType {
	return MsgJointControllerState
}

func (m *JointControllerState) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// SetPoint
	binary.Write(buf, binary.LittleEndian, m.SetPoint)

	// ProcessValue
	binary.Write(buf, binary.LittleEndian, m.ProcessValue)

	// ProcessValueDot
	binary.Write(buf, binary.LittleEndian, m.ProcessValueDot)

	// Error
	binary.Write(buf, binary.LittleEndian, m.Error)

	// TimeStep
	binary.Write(buf, binary.LittleEndian, m.TimeStep)

	// Command
	binary.Write(buf, binary.LittleEndian, m.Command)

	// P
	binary.Write(buf, binary.LittleEndian, m.P)

	// I
	binary.Write(buf, binary.LittleEndian, m.I)

	// D
	binary.Write(buf, binary.LittleEndian, m.D)

	// IClamp
	binary.Write(buf, binary.LittleEndian, m.IClamp)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// SetPoint
	if err = binary.Read(buf, binary.LittleEndian, &m.SetPoint); err != nil {
		return err
	}

	// ProcessValue
	if err = binary.Read(buf, binary.LittleEndian, &m.ProcessValue); err != nil {
		return err
	}

	// ProcessValueDot
	if err = binary.Read(buf, binary.LittleEndian, &m.ProcessValueDot); err != nil {
		return err
	}

	// Error
	if err = binary.Read(buf, binary.LittleEndian, &m.Error); err != nil {
		return err
	}

	// TimeStep
	if err = binary.Read(buf, binary.LittleEndian, &m.TimeStep); err != nil {
		return err
	}

	// Command
	if err = binary.Read(buf, binary.LittleEndian, &m.Command); err != nil {
		return err
	}

	// P
	if err = binary.Read(buf, binary.LittleEndian, &m.P); err != nil {
		return err
	}

	// I
	if err = binary.Read(buf, binary.LittleEndian, &m.I); err != nil {
		return err
	}

	// D
	if err = binary.Read(buf, binary.LittleEndian, &m.D); err != nil {
		return err
	}

	// IClamp
	if err = binary.Read(buf, binary.LittleEndian, &m.IClamp); err != nil {
		return err
	}

	return
}
