// Code generated by ros-gen-go.
// source: JointTrajectoryActionFeedback.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgJointTrajectoryActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryActionFeedback) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryActionFeedback) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryActionFeedback) NewMessage() ros.Message {
	m := new(JointTrajectoryActionFeedback)

	return m
}

var (
	MsgJointTrajectoryActionFeedback = &_MsgJointTrajectoryActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
JointTrajectoryFeedback feedback
`,
		"control_msgs/JointTrajectoryActionFeedback",
		"809ada2f6b1ce9b57876bfef3d8611f8",
	}
)

type JointTrajectoryActionFeedback struct {
	Header   std_msgs.Header
	Status   actionlib_msgs.GoalStatus
	Feedback JointTrajectoryFeedback
}

func (m *JointTrajectoryActionFeedback) Type() ros.MessageType {
	return MsgJointTrajectoryActionFeedback
}

func (m *JointTrajectoryActionFeedback) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "JointTrajectoryFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}

func (m *JointTrajectoryActionFeedback) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Feedback
	if err = ros.DeserializeMessageField(r, "JointTrajectoryFeedback", &m.Feedback); err != nil {
		return err
	}

	return
}
