// Code generated by ros-gen-go.
// source: JointControllerState.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgJointControllerState struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointControllerState) Text() string {
	return t.text
}

func (t *_MsgJointControllerState) Name() string {
	return t.name
}

func (t *_MsgJointControllerState) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointControllerState) NewMessage() ros.Message {
	m := new(JointControllerState)

	return m
}

var (
	MsgJointControllerState = &_MsgJointControllerState{
		`Header header
float64 set_point
float64 process_value
float64 process_value_dot
float64 error
float64 time_step
float64 command
float64 p
float64 i
float64 d
float64 i_clamp

`,
		"control_msgs/JointControllerState",
		"8bdc19d6058e1654165f129c40b1bc86",
	}
)

type JointControllerState struct {
	Header          std_msgs.Header
	SetPoint        float64
	ProcessValue    float64
	ProcessValueDot float64
	Error           float64
	TimeStep        float64
	Command         float64
	P               float64
	I               float64
	D               float64
	IClamp          float64
}

func (m *JointControllerState) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.SetPoint); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.ProcessValue); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.ProcessValueDot); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Error); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.TimeStep); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Command); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.P); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.I); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.D); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.IClamp); err != nil {
		return err
	}

	return
}

func (m *JointControllerState) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// SetPoint
	if err = ros.DeserializeMessageField(r, "float64", &m.SetPoint); err != nil {
		return err
	}

	// ProcessValue
	if err = ros.DeserializeMessageField(r, "float64", &m.ProcessValue); err != nil {
		return err
	}

	// ProcessValueDot
	if err = ros.DeserializeMessageField(r, "float64", &m.ProcessValueDot); err != nil {
		return err
	}

	// Error
	if err = ros.DeserializeMessageField(r, "float64", &m.Error); err != nil {
		return err
	}

	// TimeStep
	if err = ros.DeserializeMessageField(r, "float64", &m.TimeStep); err != nil {
		return err
	}

	// Command
	if err = ros.DeserializeMessageField(r, "float64", &m.Command); err != nil {
		return err
	}

	// P
	if err = ros.DeserializeMessageField(r, "float64", &m.P); err != nil {
		return err
	}

	// I
	if err = ros.DeserializeMessageField(r, "float64", &m.I); err != nil {
		return err
	}

	// D
	if err = ros.DeserializeMessageField(r, "float64", &m.D); err != nil {
		return err
	}

	// IClamp
	if err = ros.DeserializeMessageField(r, "float64", &m.IClamp); err != nil {
		return err
	}

	return
}
