// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//JointTrajectoryActionResult.msg
// DO NOT EDIT!
package control_msgs

type _MsgJointTrajectoryActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryActionResult) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryActionResult) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryActionResult) NewMessage() ros.Message {
	m := new(JointTrajectoryActionResult)

	return m
}

var (
	MsgJointTrajectoryActionResult = &_MsgJointTrajectoryActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
JointTrajectoryResult result
`,
		"control_msgs/JointTrajectoryActionResult",
		"7a08e1a1afd919c1290f681fe7f26d49",
	}
)

type JointTrajectoryActionResult struct {
	Header Header
	Status actionlib_msgs.GoalStatus
	Result JointTrajectoryResult
}

func (m *JointTrajectoryActionResult) Type() ros.MessageType {
	return MsgJointTrajectoryActionResult
}

func (m *JointTrajectoryActionResult) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}

	return
}
