// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//JointTrajectoryFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgJointTrajectoryFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryFeedback) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryFeedback) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryFeedback) NewMessage() ros.Message {
	m := new(JointTrajectoryFeedback)

	return m
}

var (
	MsgJointTrajectoryFeedback = &_MsgJointTrajectoryFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

`,
		"control_msgs/JointTrajectoryFeedback",
		"8caa57ae31d0a78f6b633986943eda51",
	}
)

type JointTrajectoryFeedback struct {
}

func (m *JointTrajectoryFeedback) Type() ros.MessageType {
	return MsgJointTrajectoryFeedback
}

func (m *JointTrajectoryFeedback) Serialize(buf *bytes.Buffer) (err error) {
	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	return
}
