// Code generated by ros-gen-go.
// source: PointHeadActionResult.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
	"github.com/ppg/rosgo/ros"
)

type _MsgPointHeadActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadActionResult) Text() string {
	return t.text
}

func (t *_MsgPointHeadActionResult) Name() string {
	return t.name
}

func (t *_MsgPointHeadActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadActionResult) NewMessage() ros.Message {
	m := new(PointHeadActionResult)

	return m
}

var (
	MsgPointHeadActionResult = &_MsgPointHeadActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
PointHeadResult result
`,
		"control_msgs/PointHeadActionResult",
		"fd218e33f1da05c36eb543bbe2970d23",
	}
)

type PointHeadActionResult struct {
	Header std_msgs.Header
	Status actionlib_msgs.GoalStatus
	Result PointHeadResult
}

func (m *PointHeadActionResult) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "PointHeadResult", &m.Result); err != nil {
		return err
	}

	return
}

func (m *PointHeadActionResult) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "PointHeadResult", &m.Result); err != nil {
		return err
	}

	return
}
