// Code generated by ros-gen-go.
// source: PointHeadResult.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgPointHeadResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadResult) Text() string {
	return t.text
}

func (t *_MsgPointHeadResult) Name() string {
	return t.name
}

func (t *_MsgPointHeadResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadResult) NewMessage() ros.Message {
	m := new(PointHeadResult)

	return m
}

var (
	MsgPointHeadResult = &_MsgPointHeadResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
`,
		"control_msgs/PointHeadResult",
		"7ac3b32c97133caf1b14edc99a50c37d",
	}
)

type PointHeadResult struct {
}

func (m *PointHeadResult) Type() ros.MessageType {
	return MsgPointHeadResult
}

func (m *PointHeadResult) Serialize(w io.Writer) (err error) {
	return
}

func (m *PointHeadResult) Deserialize(r io.Reader) (err error) {
	return
}
