// Code generated by ros-gen-go.
// source: PointHeadAction.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgPointHeadAction struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadAction) Text() string {
	return t.text
}

func (t *_MsgPointHeadAction) Name() string {
	return t.name
}

func (t *_MsgPointHeadAction) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadAction) NewMessage() ros.Message {
	m := new(PointHeadAction)

	return m
}

var (
	MsgPointHeadAction = &_MsgPointHeadAction{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

PointHeadActionGoal action_goal
PointHeadActionResult action_result
PointHeadActionFeedback action_feedback
`,
		"control_msgs/PointHeadAction",
		"8d39aaeed5e9bfedc46fa857fb471ebf",
	}
)

type PointHeadAction struct {
	ActionGoal     PointHeadActionGoal
	ActionResult   PointHeadActionResult
	ActionFeedback PointHeadActionFeedback
}

func (m *PointHeadAction) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "PointHeadActionGoal", &m.ActionGoal); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "PointHeadActionResult", &m.ActionResult); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "PointHeadActionFeedback", &m.ActionFeedback); err != nil {
		return err
	}

	return
}

func (m *PointHeadAction) Deserialize(r io.Reader) (err error) {
	// ActionGoal
	if err = ros.DeserializeMessageField(r, "PointHeadActionGoal", &m.ActionGoal); err != nil {
		return err
	}

	// ActionResult
	if err = ros.DeserializeMessageField(r, "PointHeadActionResult", &m.ActionResult); err != nil {
		return err
	}

	// ActionFeedback
	if err = ros.DeserializeMessageField(r, "PointHeadActionFeedback", &m.ActionFeedback); err != nil {
		return err
	}

	return
}
