// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//PointHeadActionResult.msg
// DO NOT EDIT!
package control_msgs

type _MsgPointHeadActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadActionResult) Text() string {
	return t.text
}

func (t *_MsgPointHeadActionResult) Name() string {
	return t.name
}

func (t *_MsgPointHeadActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadActionResult) NewMessage() ros.Message {
	m := new(PointHeadActionResult)

	return m
}

var (
	MsgPointHeadActionResult = &_MsgPointHeadActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
PointHeadResult result
`,
		"control_msgs/PointHeadActionResult",
		"fd218e33f1da05c36eb543bbe2970d23",
	}
)

type PointHeadActionResult struct {
	Header Header
	Status actionlib_msgs.GoalStatus
	Result PointHeadResult
}

func (m *PointHeadActionResult) Type() ros.MessageType {
	return MsgPointHeadActionResult
}

func (m *PointHeadActionResult) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}

	return
}
