// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//PointHeadAction.msg
// DO NOT EDIT!
package control_msgs

type _MsgPointHeadAction struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadAction) Text() string {
	return t.text
}

func (t *_MsgPointHeadAction) Name() string {
	return t.name
}

func (t *_MsgPointHeadAction) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadAction) NewMessage() ros.Message {
	m := new(PointHeadAction)

	return m
}

var (
	MsgPointHeadAction = &_MsgPointHeadAction{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

PointHeadActionGoal action_goal
PointHeadActionResult action_result
PointHeadActionFeedback action_feedback
`,
		"control_msgs/PointHeadAction",
		"8d39aaeed5e9bfedc46fa857fb471ebf",
	}
)

type PointHeadAction struct {
	ActionGoal     PointHeadActionGoal
	ActionResult   PointHeadActionResult
	ActionFeedback PointHeadActionFeedback
}

func (m *PointHeadAction) Type() ros.MessageType {
	return MsgPointHeadAction
}

func (m *PointHeadAction) Serialize(buf *bytes.Buffer) (err error) {
	// ActionGoal
	if err = m.ActionGoal.Serialize(buf); err != nil {
		return err
	}

	// ActionResult
	if err = m.ActionResult.Serialize(buf); err != nil {
		return err
	}

	// ActionFeedback
	if err = m.ActionFeedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// ActionGoal
	if err = m.ActionGoal.Deserialize(buf); err != nil {
		return err
	}

	// ActionResult
	if err = m.ActionResult.Deserialize(buf); err != nil {
		return err
	}

	// ActionFeedback
	if err = m.ActionFeedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
