// Code generated by ros-gen-go.
// source: PointHeadActionGoal.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
	"github.com/ppg/rosgo/ros"
)

type _MsgPointHeadActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPointHeadActionGoal) Text() string {
	return t.text
}

func (t *_MsgPointHeadActionGoal) Name() string {
	return t.name
}

func (t *_MsgPointHeadActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPointHeadActionGoal) NewMessage() ros.Message {
	m := new(PointHeadActionGoal)

	return m
}

var (
	MsgPointHeadActionGoal = &_MsgPointHeadActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
PointHeadGoal goal
`,
		"control_msgs/PointHeadActionGoal",
		"d2151cff361301782a6ae486c4db45ab",
	}
)

type PointHeadActionGoal struct {
	Header std_msgs.Header
	GoalID actionlib_msgs.GoalID
	Goal   PointHeadGoal
}

func (m *PointHeadActionGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "PointHeadGoal", &m.Goal); err != nil {
		return err
	}

	return
}

func (m *PointHeadActionGoal) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// GoalID
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	// Goal
	if err = ros.DeserializeMessageField(r, "PointHeadGoal", &m.Goal); err != nil {
		return err
	}

	return
}
