// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//SingleJointPositionActionResult.msg
// DO NOT EDIT!
package control_msgs

type _MsgSingleJointPositionActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionActionResult) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionActionResult) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionActionResult) NewMessage() ros.Message {
	m := new(SingleJointPositionActionResult)

	return m
}

var (
	MsgSingleJointPositionActionResult = &_MsgSingleJointPositionActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
SingleJointPositionResult result
`,
		"control_msgs/SingleJointPositionActionResult",
		"721bbe2e50a90049a415db83086873b8",
	}
)

type SingleJointPositionActionResult struct {
	Header Header
	Status actionlib_msgs.GoalStatus
	Result SingleJointPositionResult
}

func (m *SingleJointPositionActionResult) Type() ros.MessageType {
	return MsgSingleJointPositionActionResult
}

func (m *SingleJointPositionActionResult) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}

	return
}
