// Code generated by ros-gen-go.
// source: SingleJointPositionFeedback.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgSingleJointPositionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionFeedback) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionFeedback) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionFeedback) NewMessage() ros.Message {
	m := new(SingleJointPositionFeedback)

	return m
}

var (
	MsgSingleJointPositionFeedback = &_MsgSingleJointPositionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
Header header
float64 position
float64 velocity
float64 error

`,
		"control_msgs/SingleJointPositionFeedback",
		"19f3192c841f11fa1c6f55b158c637bc",
	}
)

type SingleJointPositionFeedback struct {
	Header   std_msgs.Header
	Position float64
	Velocity float64
	Error    float64
}

func (m *SingleJointPositionFeedback) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Position); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Velocity); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Error); err != nil {
		return err
	}

	return
}

func (m *SingleJointPositionFeedback) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Position
	if err = ros.DeserializeMessageField(r, "float64", &m.Position); err != nil {
		return err
	}

	// Velocity
	if err = ros.DeserializeMessageField(r, "float64", &m.Velocity); err != nil {
		return err
	}

	// Error
	if err = ros.DeserializeMessageField(r, "float64", &m.Error); err != nil {
		return err
	}

	return
}
