// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//SingleJointPositionActionFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgSingleJointPositionActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionActionFeedback) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionActionFeedback) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionActionFeedback) NewMessage() ros.Message {
	m := new(SingleJointPositionActionFeedback)

	return m
}

var (
	MsgSingleJointPositionActionFeedback = &_MsgSingleJointPositionActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
SingleJointPositionFeedback feedback
`,
		"control_msgs/SingleJointPositionActionFeedback",
		"c6315392b6d3665cedcdbb7e1bca23f9",
	}
)

type SingleJointPositionActionFeedback struct {
	Header   Header
	Status   actionlib_msgs.GoalStatus
	Feedback SingleJointPositionFeedback
}

func (m *SingleJointPositionActionFeedback) Type() ros.MessageType {
	return MsgSingleJointPositionActionFeedback
}

func (m *SingleJointPositionActionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
