// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//SingleJointPositionFeedback.msg
// DO NOT EDIT!
package control_msgs

type _MsgSingleJointPositionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionFeedback) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionFeedback) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionFeedback) NewMessage() ros.Message {
	m := new(SingleJointPositionFeedback)

	return m
}

var (
	MsgSingleJointPositionFeedback = &_MsgSingleJointPositionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
Header header
float64 position
float64 velocity
float64 error

`,
		"control_msgs/SingleJointPositionFeedback",
		"19f3192c841f11fa1c6f55b158c637bc",
	}
)

type SingleJointPositionFeedback struct {
	Header   Header
	Position float64
	Velocity float64
	Error    float64
}

func (m *SingleJointPositionFeedback) Type() ros.MessageType {
	return MsgSingleJointPositionFeedback
}

func (m *SingleJointPositionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Position
	binary.Write(buf, binary.LittleEndian, m.Position)

	// Velocity
	binary.Write(buf, binary.LittleEndian, m.Velocity)

	// Error
	binary.Write(buf, binary.LittleEndian, m.Error)

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Position
	if err = binary.Read(buf, binary.LittleEndian, &m.Position); err != nil {
		return err
	}

	// Velocity
	if err = binary.Read(buf, binary.LittleEndian, &m.Velocity); err != nil {
		return err
	}

	// Error
	if err = binary.Read(buf, binary.LittleEndian, &m.Error); err != nil {
		return err
	}

	return
}
