// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../control_msgs/msg//SingleJointPositionResult.msg
// DO NOT EDIT!
package control_msgs

type _MsgSingleJointPositionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionResult) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionResult) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionResult) NewMessage() ros.Message {
	m := new(SingleJointPositionResult)

	return m
}

var (
	MsgSingleJointPositionResult = &_MsgSingleJointPositionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
`,
		"control_msgs/SingleJointPositionResult",
		"7ac3b32c97133caf1b14edc99a50c37d",
	}
)

type SingleJointPositionResult struct {
}

func (m *SingleJointPositionResult) Type() ros.MessageType {
	return MsgSingleJointPositionResult
}

func (m *SingleJointPositionResult) Serialize(buf *bytes.Buffer) (err error) {
	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	return
}
