// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../nav_msgs/msg//GetMapActionFeedback.msg
// DO NOT EDIT!
package nav_msgs

type _MsgGetMapActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionFeedback) Text() string {
	return t.text
}

func (t *_MsgGetMapActionFeedback) Name() string {
	return t.name
}

func (t *_MsgGetMapActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionFeedback) NewMessage() ros.Message {
	m := new(GetMapActionFeedback)

	return m
}

var (
	MsgGetMapActionFeedback = &_MsgGetMapActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapFeedback feedback
`,
		"nav_msgs/GetMapActionFeedback",
		"b1903ca2aba7657e9ae2ee27e803be66",
	}
)

type GetMapActionFeedback struct {
	Header   Header
	Status   actionlib_msgs.GoalStatus
	Feedback GetMapFeedback
}

func (m *GetMapActionFeedback) Type() ros.MessageType {
	return MsgGetMapActionFeedback
}

func (m *GetMapActionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
