// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../nav_msgs/msg//GetMapActionResult.msg
// DO NOT EDIT!
package nav_msgs

type _MsgGetMapActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionResult) Text() string {
	return t.text
}

func (t *_MsgGetMapActionResult) Name() string {
	return t.name
}

func (t *_MsgGetMapActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionResult) NewMessage() ros.Message {
	m := new(GetMapActionResult)

	return m
}

var (
	MsgGetMapActionResult = &_MsgGetMapActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapResult result
`,
		"nav_msgs/GetMapActionResult",
		"68a3f57ae795f2558128749b8138124b",
	}
)

type GetMapActionResult struct {
	Header Header
	Status actionlib_msgs.GoalStatus
	Result GetMapResult
}

func (m *GetMapActionResult) Type() ros.MessageType {
	return MsgGetMapActionResult
}

func (m *GetMapActionResult) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}

	return
}
