// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../nav_msgs/msg//GetMapActionGoal.msg
// DO NOT EDIT!
package nav_msgs

type _MsgGetMapActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionGoal) Text() string {
	return t.text
}

func (t *_MsgGetMapActionGoal) Name() string {
	return t.name
}

func (t *_MsgGetMapActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionGoal) NewMessage() ros.Message {
	m := new(GetMapActionGoal)

	return m
}

var (
	MsgGetMapActionGoal = &_MsgGetMapActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GetMapGoal goal
`,
		"nav_msgs/GetMapActionGoal",
		"ce89bc7a81ab5735d0eb84f8878348f1",
	}
)

type GetMapActionGoal struct {
	Header Header
	GoalID actionlib_msgs.GoalID
	Goal   GetMapGoal
}

func (m *GetMapActionGoal) Type() ros.MessageType {
	return MsgGetMapActionGoal
}

func (m *GetMapActionGoal) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Serialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Deserialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}

	return
}
