// Code generated by ros-gen-go.
// source: GetMapActionGoal.msg
// DO NOT EDIT!
package nav_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgGetMapActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionGoal) Text() string {
	return t.text
}

func (t *_MsgGetMapActionGoal) Name() string {
	return t.name
}

func (t *_MsgGetMapActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionGoal) NewMessage() ros.Message {
	m := new(GetMapActionGoal)

	return m
}

var (
	MsgGetMapActionGoal = &_MsgGetMapActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GetMapGoal goal
`,
		"nav_msgs/GetMapActionGoal",
		"ce89bc7a81ab5735d0eb84f8878348f1",
	}
)

type GetMapActionGoal struct {
	Header std_msgs.Header
	GoalID actionlib_msgs.GoalID
	Goal   GetMapGoal
}

func (m *GetMapActionGoal) Type() ros.MessageType {
	return MsgGetMapActionGoal
}

func (m *GetMapActionGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "GetMapGoal", &m.Goal); err != nil {
		return err
	}

	return
}

func (m *GetMapActionGoal) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// GoalID
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	// Goal
	if err = ros.DeserializeMessageField(r, "GetMapGoal", &m.Goal); err != nil {
		return err
	}

	return
}
