// Code generated by ros-gen-go.
// source: GetMapActionResult.msg
// DO NOT EDIT!
package nav_msgs

import (
	"io"

	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
	"github.com/ppg/rosgo/ros"
)

type _MsgGetMapActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionResult) Text() string {
	return t.text
}

func (t *_MsgGetMapActionResult) Name() string {
	return t.name
}

func (t *_MsgGetMapActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionResult) NewMessage() ros.Message {
	m := new(GetMapActionResult)

	return m
}

var (
	MsgGetMapActionResult = &_MsgGetMapActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapResult result
`,
		"nav_msgs/GetMapActionResult",
		"68a3f57ae795f2558128749b8138124b",
	}
)

type GetMapActionResult struct {
	Header std_msgs.Header
	Status actionlib_msgs.GoalStatus
	Result GetMapResult
}

func (m *GetMapActionResult) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "GetMapResult", &m.Result); err != nil {
		return err
	}

	return
}

func (m *GetMapActionResult) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "GetMapResult", &m.Result); err != nil {
		return err
	}

	return
}
