// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../nav_msgs/msg//GetMapFeedback.msg
// DO NOT EDIT!
package nav_msgs

type _MsgGetMapFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapFeedback) Text() string {
	return t.text
}

func (t *_MsgGetMapFeedback) Name() string {
	return t.name
}

func (t *_MsgGetMapFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapFeedback) NewMessage() ros.Message {
	m := new(GetMapFeedback)

	return m
}

var (
	MsgGetMapFeedback = &_MsgGetMapFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# no feedback
`,
		"nav_msgs/GetMapFeedback",
		"77f7066d632b7ec3bba7d2cf876a3746",
	}
)

type GetMapFeedback struct {
}

func (m *GetMapFeedback) Type() ros.MessageType {
	return MsgGetMapFeedback
}

func (m *GetMapFeedback) Serialize(buf *bytes.Buffer) (err error) {
	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	return
}
