// Code generated by ros-gen-go.
// source: Path.msg
// DO NOT EDIT!
package nav_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/ppg/rosgo/msgs/geometry_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
	"github.com/ppg/rosgo/ros"
)

type _MsgPath struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPath) Text() string {
	return t.text
}

func (t *_MsgPath) Name() string {
	return t.name
}

func (t *_MsgPath) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPath) NewMessage() ros.Message {
	m := new(Path)

	return m
}

var (
	MsgPath = &_MsgPath{
		`#An array of poses that represents a Path for a robot to follow
Header header
geometry_msgs/PoseStamped[] poses
`,
		"nav_msgs/Path",
		"ec86ae50c777497b60186b87d59a8808",
	}
)

type Path struct {
	Header std_msgs.Header
	Poses  []geometry_msgs.PoseStamped
}

func (m *Path) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Poses)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Poses {
		if err = ros.SerializeMessageField(w, "geometry_msgs/PoseStamped", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *Path) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Poses
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Poses: %s", err)
		}
		m.Poses = make([]geometry_msgs.PoseStamped, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "geometry_msgs/PoseStamped", &m.Poses[i]); err != nil {
				return err
			}
		}
	}

	return
}
