// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../tf2_msgs/msg//LookupTransformActionFeedback.msg
// DO NOT EDIT!
package tf2_msgs

type _MsgLookupTransformActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionFeedback) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionFeedback) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionFeedback) NewMessage() ros.Message {
	m := new(LookupTransformActionFeedback)

	return m
}

var (
	MsgLookupTransformActionFeedback = &_MsgLookupTransformActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
LookupTransformFeedback feedback
`,
		"tf2_msgs/LookupTransformActionFeedback",
		"bb3a8cf9a930b87557ce3ec96e51106f",
	}
)

type LookupTransformActionFeedback struct {
	Header   Header
	Status   actionlib_msgs.GoalStatus
	Feedback LookupTransformFeedback
}

func (m *LookupTransformActionFeedback) Type() ros.MessageType {
	return MsgLookupTransformActionFeedback
}

func (m *LookupTransformActionFeedback) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Feedback
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}

	return
}
