// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../tf2_msgs/msg//LookupTransformActionResult.msg
// DO NOT EDIT!
package tf2_msgs

type _MsgLookupTransformActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionResult) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionResult) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionResult) NewMessage() ros.Message {
	m := new(LookupTransformActionResult)

	return m
}

var (
	MsgLookupTransformActionResult = &_MsgLookupTransformActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
LookupTransformResult result
`,
		"tf2_msgs/LookupTransformActionResult",
		"244c023081ddbc63593feb4550984b44",
	}
)

type LookupTransformActionResult struct {
	Header Header
	Status actionlib_msgs.GoalStatus
	Result LookupTransformResult
}

func (m *LookupTransformActionResult) Type() ros.MessageType {
	return MsgLookupTransformActionResult
}

func (m *LookupTransformActionResult) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// Status
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}

	// Result
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}

	return
}
