// Code generated by ros-gen-go.
// source: LookupTransformActionGoal.msg
// DO NOT EDIT!
package tf2_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
	"github.com/ppg/rosgo/msgs/actionlib_msgs"
	"github.com/ppg/rosgo/msgs/std_msgs"
)

type _MsgLookupTransformActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionGoal) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionGoal) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionGoal) NewMessage() ros.Message {
	m := new(LookupTransformActionGoal)

	return m
}

var (
	MsgLookupTransformActionGoal = &_MsgLookupTransformActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
LookupTransformGoal goal
`,
		"tf2_msgs/LookupTransformActionGoal",
		"0dc122e6d207537854c1091c7efaea8b",
	}
)

type LookupTransformActionGoal struct {
	Header std_msgs.Header
	GoalID actionlib_msgs.GoalID
	Goal   LookupTransformGoal
}

func (m *LookupTransformActionGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "LookupTransformGoal", &m.Goal); err != nil {
		return err
	}

	return
}

func (m *LookupTransformActionGoal) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// GoalID
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalID", &m.GoalID); err != nil {
		return err
	}

	// Goal
	if err = ros.DeserializeMessageField(r, "LookupTransformGoal", &m.Goal); err != nil {
		return err
	}

	return
}
