// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../tf2_msgs/msg//LookupTransformActionGoal.msg
// DO NOT EDIT!
package tf2_msgs

type _MsgLookupTransformActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionGoal) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionGoal) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionGoal) NewMessage() ros.Message {
	m := new(LookupTransformActionGoal)

	return m
}

var (
	MsgLookupTransformActionGoal = &_MsgLookupTransformActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
LookupTransformGoal goal
`,
		"tf2_msgs/LookupTransformActionGoal",
		"0dc122e6d207537854c1091c7efaea8b",
	}
)

type LookupTransformActionGoal struct {
	Header Header
	GoalID actionlib_msgs.GoalID
	Goal   LookupTransformGoal
}

func (m *LookupTransformActionGoal) Type() ros.MessageType {
	return MsgLookupTransformActionGoal
}

func (m *LookupTransformActionGoal) Serialize(buf *bytes.Buffer) (err error) {
	// Header
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Serialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Header
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}

	// GoalID
	if err = m.GoalID.Deserialize(buf); err != nil {
		return err
	}

	// Goal
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}

	return
}
