// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../tf2_msgs/msg//LookupTransformResult.msg
// DO NOT EDIT!
package tf2_msgs

type _MsgLookupTransformResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformResult) Text() string {
	return t.text
}

func (t *_MsgLookupTransformResult) Name() string {
	return t.name
}

func (t *_MsgLookupTransformResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformResult) NewMessage() ros.Message {
	m := new(LookupTransformResult)

	return m
}

var (
	MsgLookupTransformResult = &_MsgLookupTransformResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
geometry_msgs/TransformStamped transform
tf2_msgs/TF2Error error
`,
		"tf2_msgs/LookupTransformResult",
		"1b424b9cebdb0bd3b355dd47a6c2cdca",
	}
)

type LookupTransformResult struct {
	Transform geometry_msgs.TransformStamped
	Error     TF2Error
}

func (m *LookupTransformResult) Type() ros.MessageType {
	return MsgLookupTransformResult
}

func (m *LookupTransformResult) Serialize(buf *bytes.Buffer) (err error) {
	// Transform
	if err = m.Transform.Serialize(buf); err != nil {
		return err
	}

	// Error
	if err = m.Error.Serialize(buf); err != nil {
		return err
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Transform
	if err = m.Transform.Deserialize(buf); err != nil {
		return err
	}

	// Error
	if err = m.Error.Deserialize(buf); err != nil {
		return err
	}

	return
}
