// Code generated by ros-gen-go.
// source: /opt/ros/jade/share/ros/../tf2_msgs/msg//TFMessage.msg
// DO NOT EDIT!
package tf2_msgs

type _MsgTFMessage struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgTFMessage) Text() string {
	return t.text
}

func (t *_MsgTFMessage) Name() string {
	return t.name
}

func (t *_MsgTFMessage) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgTFMessage) NewMessage() ros.Message {
	m := new(TFMessage)

	return m
}

var (
	MsgTFMessage = &_MsgTFMessage{
		`geometry_msgs/TransformStamped[] transforms
`,
		"tf2_msgs/TFMessage",
		"996e2194fbbcbb59e036b104dcc9f6fb",
	}
)

type TFMessage struct {
	Transforms []geometry_msgs.TransformStamped
}

func (m *TFMessage) Type() ros.MessageType {
	return MsgTFMessage
}

func (m *TFMessage) Serialize(buf *bytes.Buffer) (err error) {
	// Transforms
	binary.Write(buf, binary.LittleEndian, uint32(len(m.Transforms)))
	for _, e := range m.Transforms {
		if err = e.Serialize(buf); err != nil {
			return err
		}
	}

	return
}

func (m *String) Deserialize(buf *bytes.Reader) (err error) {
	// Transforms
	var size uint32
	if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
		return err
	}
	m.Transforms = make([]geometry_msgs.TransformStamped, int(size))
	for i := 0; i < int(size); i++ {
		if err = m.Transforms[i].Deserialize(buf); err != nil {
			return err
		}
	}

	return
}
