// Code generated by ros-gen-go.
// source: ../msg/Hello.msg
// DO NOT EDIT!
package msgs

import (
	"bytes"
	"encoding/binary"

	"github.com/ppg/rosgo/ros"
)

type _MsgHello struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgHello) Text() string {
	return t.text
}

func (t *_MsgHello) Name() string {
	return t.name
}

func (t *_MsgHello) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgHello) NewMessage() ros.Message {
	m := new(Hello)

	return m
}

var (
	MsgHello = &_MsgHello{
		`string data
`,
		"msgs/Hello",
		"5b89344b4d080ca499c0648063c40738",
	}
)

type Hello struct {
	Data string
}

func (m *Hello) Type() ros.MessageType {
	return MsgHello
}

func (m *Hello) Serialize(buf *bytes.Buffer) (err error) {
	// Data
	binary.Write(buf, binary.LittleEndian, uint32(len([]byte(m.Data))))
	buf.Write([]byte(m.Data))

	return
}

func (m *Hello) Deserialize(buf *bytes.Reader) (err error) {
	// Data
	{
		var size uint32
		if err = binary.Read(buf, binary.LittleEndian, &size); err != nil {
			return err
		}
		data := make([]byte, int(size))
		if err = binary.Read(buf, binary.LittleEndian, data); err != nil {
			return err
		}
		m.Data = string(data)
	}

	return
}
