// Code generated by ros-gen-go.
// source: KeyValue.msg
// DO NOT EDIT!
package diagnostic_msgs

import (
	"io"

	"github.com/ppg/rosgo/ros"
)

type _MsgKeyValue struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgKeyValue) Text() string {
	return t.text
}

func (t *_MsgKeyValue) Name() string {
	return t.name
}

func (t *_MsgKeyValue) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgKeyValue) NewMessage() ros.Message {
	m := new(KeyValue)

	return m
}

var (
	MsgKeyValue = &_MsgKeyValue{
		`string key # what to label this value when viewing
string value # a value to track over time
`,
		"diagnostic_msgs/KeyValue",
		"f42b961af7f6947ab0f9555f47ecb4d4",
	}
)

type KeyValue struct {
	Key   string
	Value string
}

func (m *KeyValue) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.Key); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.Value); err != nil {
		return err
	}

	return
}

func (m *KeyValue) Deserialize(r io.Reader) (err error) {
	// Key
	if err = ros.DeserializeMessageField(r, "string", &m.Key); err != nil {
		return err
	}

	// Value
	if err = ros.DeserializeMessageField(r, "string", &m.Value); err != nil {
		return err
	}

	return
}
